#!/usr/bin/env bash
#
# Bazzite (GNOME) post-install setup
# Flatpak for GUI apps; rpm-ostree layering for CLI/system tools only.
# Signal uses the official AppImage (GPG-verified).
#
# Bazzite already ships with: Steam, GPU drivers (incl. NVIDIA), multimedia
# codecs, RPMFusion repos, and auto-updates — those sections from the regular
# Fedora script are omitted entirely.
#
# Usage (fresh install): download this ONE file and run it as your normal user
# inside a GNOME session. Don't pipe it to bash from curl — download, read, run:
#   curl -fLO https://raw.githubusercontent.com/<you>/<repo>/main/bazzite_stuff.sh
#   chmod +x bazzite_stuff.sh && ./bazzite_stuff.sh
# Everything else (updaters, PKI importers, verifiers) is generated by this
# script into ~/.local/bin and /etc/systemd — nothing else to check out.
#
set -euo pipefail

if [ "$EUID" -eq 0 ]; then
  echo "Don't run this with sudo / as root. Run it as your normal user:" >&2
  echo "    ./bazzite_stuff.sh" >&2
  echo "It will prompt for your password when it reaches the first sudo step." >&2
  exit 1
fi

if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
  echo "No D-Bus session bus found (DBUS_SESSION_BUS_ADDRESS is unset)." >&2
  echo "This script sets GNOME preferences with gsettings and must run inside a" >&2
  echo "graphical GNOME session — not over SSH or a plain TTY. Log in to the" >&2
  echo "desktop, open a terminal there, and re-run it." >&2
  exit 1
fi

#
# Flatpak GUI apps (Flathub is pre-configured on Bazzite)
#
flatpak install --noninteractive flathub \
  com.visualstudio.code \
  com.microsoft.Edge \
  com.google.Chrome \
  org.videolan.VLC \
  org.ferdium.Ferdium \
  ca.desrt.dconf-editor

#
# rpm-ostree layering — CLI tools, GNOME shell extensions, and system-level
# packages in a single transaction.
#   --idempotent: succeed even if packages are already in the base image.
#   --apply-live: make layered packages available immediately without rebooting.
# If --apply-live fails (rare), the packages are staged for the next boot and
# the script continues with user-space setup.
#
OSTREE_OK=1
if ! sudo rpm-ostree install --idempotent --apply-live \
  gnome-shell-extension-common gnome-shell-extension-user-theme \
  gnome-shell-extension-freon gnome-shell-extension-no-overview \
  gnome-shell-extension-dash-to-dock \
  gnome-shell-extension-appindicator gnome-shell-extension-caffeine \
  gnome-shell-extension-blur-my-shell gnome-shell-extension-just-perfection \
  gnome-tweaks gnome-extensions-app \
  git btop fastfetch solaar mpv \
  yt-dlp 7zip unrar \
  rsms-inter-vf-fonts \
  fuse-libs \
  ydotool pcsc-lite pcsc-lite-ccid pam-u2f pamu2fcfg yubikey-manager \
  opensc nss-tools openssl gnupg2 unzip \
  fprintd fprintd-pam \
  vim-enhanced; then
  echo "WARN: --apply-live failed; layered packages are staged for next boot."
  echo "      GNOME extensions and some CLI tools may not work until you reboot."
  OSTREE_OK=0
fi

#
# Default editor — set vim for the current user without touching the immutable
# base. Uses systemd's environment.d so it applies to all login sessions.
#
mkdir -p ~/.config/environment.d
if ! grep -q 'EDITOR=vim' ~/.config/environment.d/editor.conf 2>/dev/null; then
  echo 'EDITOR=vim' >> ~/.config/environment.d/editor.conf
fi

#
# Enable GNOME shell extensions at startup.
# Installing the RPM only drops files in /usr/share/gnome-shell/extensions;
# they still have to be added to org.gnome.shell enabled-extensions. We write
# the gsettings key directly so it works even before the shell has rescanned
# (gnome-extensions enable would refuse until then) and survives a re-login.
#
gext_enable() {
  local uuid="$1" cur new
  cur=$(gsettings get org.gnome.shell enabled-extensions)
  case "$cur" in
    *"'$uuid'"*)     ;;
    "@as []"|"[]")   gsettings set org.gnome.shell enabled-extensions "['$uuid']" ;;
    *)               gsettings set org.gnome.shell enabled-extensions "${cur%]}, '$uuid']" ;;
  esac
  cur=$(gsettings get org.gnome.shell disabled-extensions)
  if [[ "$cur" == *"'$uuid'"* ]]; then
    new=$(python3 -c 'import ast, sys
v, u = sys.argv[1], sys.argv[2]
lst = ast.literal_eval(v) if v.lstrip().startswith("[") else []
print("[" + ", ".join(repr(x) for x in lst if x != u) + "]")' "$cur" "$uuid")
    gsettings set org.gnome.shell disabled-extensions "$new"
  fi
}
gext_enable dash-to-dock@micxgx.gmail.com
gext_enable no-overview@fthx
gext_enable appindicatorsupport@rgcjonas.gmail.com
gext_enable caffeine@patapon.info
gext_enable blur-my-shell@aunetx
gext_enable just-perfection-desktop@just-perfection

#
# Signal Desktop — official AppImage (GPG-verified). No flatpak needed.
#
SIGNAL_KEY_FPR="4B16B7232DFAA439AD791002EF9F501F13EED94C"

curl -fsSL https://updates.signal.org/static/desktop/appimage.asc | gpg --import
if ! gpg --with-colons --fingerprint "$SIGNAL_KEY_FPR" 2>/dev/null \
     | grep -q "^fpr:::::::::${SIGNAL_KEY_FPR}:"; then
  echo "ERROR: Signal signing key $SIGNAL_KEY_FPR not present after import." >&2
  echo "Aborting before download." >&2
  exit 1
fi

mkdir -p ~/.local/bin
cat > ~/.local/bin/update-signal-appimage.sh <<'SIGEOF'
#!/usr/bin/env bash
set -euo pipefail

SIGNAL_KEY_FPR="4B16B7232DFAA439AD791002EF9F501F13EED94C"

curl -fsI --max-time 10 https://updates.signal.org >/dev/null 2>&1 \
  || { echo "Signal: network unreachable, skipping."; exit 0; }

dest="$HOME/Applications/Signal.AppImage"
mkdir -p "$HOME/Applications"
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
curl -fL -o "$tmp/Signal.AppImage"     https://updates.signal.org/desktop/signal-desktop.AppImage
curl -fL -o "$tmp/Signal.AppImage.gpg" https://updates.signal.org/desktop/signal-desktop.AppImage.gpg
status=$(gpg --status-fd 1 --verify "$tmp/Signal.AppImage.gpg" "$tmp/Signal.AppImage" 2>/dev/null) || true
if ! printf '%s\n' "$status" \
     | grep -aEq "^\[GNUPG:\] VALIDSIG ([0-9A-F]{40} .* )?${SIGNAL_KEY_FPR}( |$)"; then
  echo "Signal: signature not made by pinned key ${SIGNAL_KEY_FPR}; refusing to install." >&2
  exit 1
fi
if [ -f "$dest" ] && cmp -s "$tmp/Signal.AppImage" "$dest"; then
  echo "Signal already up to date."
  exit 0
fi
chmod +x "$tmp/Signal.AppImage"
mv -f "$tmp/Signal.AppImage" "$dest"
echo "Signal updated."
SIGEOF
chmod +x ~/.local/bin/update-signal-appimage.sh

~/.local/bin/update-signal-appimage.sh

mkdir -p ~/.local/share/icons
signal_icon="signal-desktop"
if [ -f ~/.local/share/icons/signal.png ]; then
  signal_icon="$HOME/.local/share/icons/signal.png"
else
  sig_tmp=$(mktemp -d)
  if ( cd "$sig_tmp" && ~/Applications/Signal.AppImage --appimage-extract >/dev/null 2>&1 ) \
     && cp -L "$sig_tmp/squashfs-root/.DirIcon" ~/.local/share/icons/signal.png 2>/dev/null; then
    signal_icon="$HOME/.local/share/icons/signal.png"
  else
    echo "WARN: could not extract Signal icon from AppImage; launcher will use the themed name."
  fi
  rm -rf "$sig_tmp"
fi

mkdir -p ~/.local/share/applications
cat > ~/.local/share/applications/signal.desktop <<EOF
[Desktop Entry]
Name=Signal
Exec=$HOME/Applications/Signal.AppImage %U
Terminal=false
Type=Application
Icon=$signal_icon
Categories=Network;InstantMessaging;Chat;
MimeType=x-scheme-handler/sgnl;x-scheme-handler/signalcaptcha;
StartupWMClass=Signal
EOF
command -v update-desktop-database &>/dev/null \
  && update-desktop-database ~/.local/share/applications || true

#
# YubiKey — lock the session when the key is removed, wake the display when it
# is inserted, and enable the smartcard daemon for PIV / GPG / ykman.
#
# /etc is a writable overlay on Bazzite (Fedora Atomic), so udev rules and
# systemd units placed there persist across rebases.
#
YDOTOOL_SOCKET_PATH="/tmp/.ydotool_socket"

ydotoold_unit="[Unit]
Description=ydotool input daemon (for YubiKey wake-on-insert udev rule)
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/ydotoold --socket-path=${YDOTOOL_SOCKET_PATH} --socket-perm=0600
Restart=on-failure

[Install]
WantedBy=multi-user.target"
if ! diff -q <(printf '%s\n' "$ydotoold_unit") /etc/systemd/system/ydotoold.service &>/dev/null; then
  printf '%s\n' "$ydotoold_unit" | sudo tee /etc/systemd/system/ydotoold.service > /dev/null
  sudo systemctl daemon-reload
fi
sudo systemctl enable --now ydotoold.service

yubikey_rules="# Lock all sessions when any YubiKey (vendor 1050) is removed
ACTION==\"remove\", ENV{ID_BUS}==\"usb\", ENV{ID_VENDOR_ID}==\"1050\", RUN+=\"/usr/bin/loginctl lock-sessions\"

# Wake the display when any YubiKey is inserted
ACTION==\"add\", ENV{ID_BUS}==\"usb\", ENV{ID_VENDOR_ID}==\"1050\", ENV{YDOTOOL_SOCKET}=\"${YDOTOOL_SOCKET_PATH}\", RUN+=\"/usr/bin/ydotool key 42:1 42:0\""
if ! diff -q <(printf '%s\n' "$yubikey_rules") /etc/udev/rules.d/80-yubikey.rules &>/dev/null; then
  printf '%s\n' "$yubikey_rules" | sudo tee /etc/udev/rules.d/80-yubikey.rules > /dev/null
  sudo udevadm control --reload
fi

sudo systemctl enable --now pcscd.socket

#
# PIV smartcard (USDA CAC-style login certs) in Chrome / Edge / Firefox
#
# opensc (layered above) ships /usr/share/p11-kit/modules/opensc.module which
# p11-kit auto-registers for NSS (Chrome/Edge/Firefox). No per-user setup needed.
#
mkdir -p ~/.local/bin
cat > ~/.local/bin/import-piv-cas.sh <<'PIVEOF'
#!/usr/bin/env bash
set -uo pipefail
DB="sql:$HOME/.pki/nssdb"
FCPCA_URL="http://repo.fpki.gov/fcpca/fcpcag2.crt"

for t in certutil pkcs11-tool opensc-tool openssl curl; do
  command -v "$t" >/dev/null 2>&1 || { echo "Missing $t — layer nss-tools/opensc/openssl/curl with rpm-ostree and reboot, then re-run." >&2; exit 1; }
done
systemctl is-active --quiet pcscd 2>/dev/null || sudo systemctl enable --now pcscd.socket 2>/dev/null || true

[ -f "$HOME/.pki/nssdb/cert9.db" ] || { mkdir -p "$HOME/.pki/nssdb"; certutil -d "$DB" -N --empty-password; }

work=$(mktemp -d); trap 'rm -rf "$work"' EXIT; cd "$work" || exit 1

if ! pkcs11-tool --read-object --type cert --id 1 >leaf.der 2>/dev/null; then
  echo "No PIV card / reader found — insert the card and retry."; exit 1
fi
openssl x509 -inform DER -in leaf.der -out leaf.pem

seen="$work/seen.txt"; : >"$seen"
import_cert() {
  local f="$1" subj iss fp nick short
  openssl x509 -in "$f" -noout >/dev/null 2>&1 || return 0
  subj=$(openssl x509 -in "$f" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$f" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  fp=$(openssl x509 -in "$f" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
  grep -qF "$fp" "$seen" && return 0; echo "$fp" >>"$seen"
  short=$(echo "$subj" | grep -oiE '(CN|OU)=[^,]+' | head -1 | cut -d= -f2-)
  nick="${short:-CA} ${fp:0:8}"
  if [ "$subj" = "$iss" ]; then
    certutil -d "$DB" -A -n "$nick" -t "CT,C,C" -i "$f" 2>/dev/null && echo "  trusted root : $nick"
  else
    certutil -d "$DB" -A -n "$nick" -t ",,"    -i "$f" 2>/dev/null && echo "  intermediate : $nick"
  fi
}

ski() { openssl x509 -in "$1" -noout -text 2>/dev/null | grep -A1 "Subject Key Identifier"   | tail -1 | tr -d ' '; }
aki() { openssl x509 -in "$1" -noout -text 2>/dev/null | grep -A1 "Authority Key Identifier" | tail -1 | tr -d ' ' | sed 's/keyid://'; }

chase() {
  local f="$1" d="${2:-0}" subj iss want u tmp certs c csub ciss best best_root chosen
  [ "$d" -gt 8 ] && return
  subj=$(openssl x509 -in "$f" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$f" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  [ "$subj" = "$iss" ] && return
  want=$(aki "$f")
  for u in $(openssl x509 -in "$f" -noout -text 2>/dev/null \
             | grep -oE 'CA Issuers - URI:http://[^ ]+' | sed 's/CA Issuers - URI://'); do
    tmp=$(mktemp); curl -fsS --max-time 20 -o "$tmp" "$u" || { rm -f "$tmp"; continue; }
    certs=$(mktemp)
    openssl pkcs7 -inform DER -in "$tmp" -print_certs 2>/dev/null >"$certs" \
      || openssl x509 -inform DER -in "$tmp" 2>/dev/null >"$certs" || { rm -f "$tmp" "$certs"; continue; }
    ( cd "$work" && awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("seg"n".pem")}' "$certs" )
    best=""; best_root=""
    for c in "$work"/seg*.pem; do
      [ -s "$c" ] || continue
      openssl x509 -in "$c" -noout >/dev/null 2>&1 || { rm -f "$c"; continue; }
      csub=$(openssl x509 -in "$c" -noout -subject -nameopt RFC2253 2>/dev/null); csub=${csub#subject=}
      ciss=$(openssl x509 -in "$c" -noout -issuer  -nameopt RFC2253 2>/dev/null); ciss=${ciss#issuer=}
      if { [ -n "$want" ] && [ "$(ski "$c")" = "$want" ]; } \
         || { [ -z "$want" ] && [ "$csub" = "$iss" ]; }; then
        if [ "$csub" = "$ciss" ]; then cp "$c" "$work/parent_root.pem"; best_root="$work/parent_root.pem"
        else                           cp "$c" "$work/parent.pem";      best="$work/parent.pem"; fi
      fi
      rm -f "$c"
    done
    rm -f "$tmp" "$certs"
    chosen="${best_root:-$best}"
    if [ -n "$chosen" ]; then
      import_cert "$chosen"; chase "$chosen" $((d+1)); rm -f "$work/parent_root.pem" "$work/parent.pem"
      return
    fi
  done
}

echo "Importing PIV CA chain into $DB ..."
chase leaf.pem 0

if curl -fsS --max-time 25 -o fcpca.crt "$FCPCA_URL"; then
  openssl x509 -inform DER -in fcpca.crt -out fcpca.pem && import_cert fcpca.pem
fi

echo
echo "nssdb CA list:"; certutil -d "$DB" -L
echo
if certutil -d "$DB" -V -u C -n "PIV_II:Certificate for PIV Authentication" </dev/null 2>/dev/null; then
  echo "OK: PIV Authentication cert validates for TLS client auth."
  echo "Restart your browser, open the USDA site, pick 'PIV Authentication', enter PIN."
else
  echo "Imported, but couldn't auto-verify the token cert (token label may differ)."
fi
PIVEOF
chmod +x ~/.local/bin/import-piv-cas.sh

#
# Federal/USDA PKI — card-free variant
#
cat > ~/.local/bin/import-federal-cas.sh <<'FEDEOF'
#!/usr/bin/env bash
set -uo pipefail
DB="sql:$HOME/.pki/nssdb"
FCPCA_URL="http://repo.fpki.gov/fcpca/fcpcag2.crt"
FCPCA_SIA_FALLBACK="http://repo.fpki.gov/fcpca/caCertsIssuedByfcpcag2.p7c"
EXTRA_SIA_SEEDS="http://rootweb.managed.entrust.com/SIA/CertsIssuedByEMSRootCA.p7c
http://rootweb.managed.entrust.com/AIA/CertsIssuedToEMSRootCA.p7c"
BRANCH_FILTER="entrust"

for t in certutil openssl curl; do
  command -v "$t" >/dev/null 2>&1 || { echo "Missing $t — layer nss-tools/openssl/curl with rpm-ostree and reboot, then re-run." >&2; exit 1; }
done
[ -f "$HOME/.pki/nssdb/cert9.db" ] || { mkdir -p "$HOME/.pki/nssdb"; certutil -d "$DB" -N --empty-password; }
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT; cd "$work" || exit 1

seen="$work/seen.txt"; : >"$seen"
import_cert() {
  local f="$1" subj iss fp nick short
  openssl x509 -in "$f" -noout >/dev/null 2>&1 || return 0
  subj=$(openssl x509 -in "$f" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$f" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  fp=$(openssl x509 -in "$f" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
  grep -qF "$fp" "$seen" && return 0; echo "$fp" >>"$seen"
  short=$(echo "$subj" | grep -oiE '(CN|OU)=[^,]+' | head -1 | cut -d= -f2-)
  nick="${short:-CA} ${fp:0:8}"
  if [ "$subj" = "$iss" ]; then
    certutil -d "$DB" -A -n "$nick" -t "CT,C,C" -i "$f" 2>/dev/null && echo "  trusted root : $nick"
  else
    certutil -d "$DB" -A -n "$nick" -t ",,"    -i "$f" 2>/dev/null && echo "  intermediate : $nick"
  fi
}

sia_urls() {
  openssl x509 -in "$1" -noout -text 2>/dev/null \
    | grep -oE 'CA Repository - URI:https?://[^ ]+' | sed 's/CA Repository - URI://'
}

process_bundle() {
  local url="$1" d="${2:-0}" tmp certs segdir c u2
  [ "$d" -gt 3 ] && return
  tmp=$(mktemp); curl -fsS --max-time 25 -o "$tmp" "$url" || { rm -f "$tmp"; return; }
  certs=$(mktemp)
  openssl pkcs7 -inform DER -in "$tmp" -print_certs 2>/dev/null >"$certs" \
    || openssl pkcs7 -in "$tmp" -print_certs 2>/dev/null >"$certs" \
    || openssl x509 -inform DER -in "$tmp" 2>/dev/null >"$certs" \
    || { rm -f "$tmp" "$certs"; return; }
  segdir=$(mktemp -d -p "$work")
  ( cd "$segdir" && awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("seg"n".pem")}' "$certs" )
  for c in "$segdir"/seg*.pem; do
    [ -s "$c" ] || continue
    openssl x509 -in "$c" -noout >/dev/null 2>&1 || continue
    import_cert "$c"
    if openssl x509 -in "$c" -noout -subject 2>/dev/null | grep -qi "$BRANCH_FILTER"; then
      for u2 in $(sia_urls "$c"); do process_bundle "$u2" $((d+1)); done
    fi
  done
  rm -rf "$tmp" "$certs" "$segdir"
}

echo "Importing Federal/USDA PIV trust chain (card-free) into $DB ..."
if ! curl -fsS --max-time 25 -o fcpca.crt "$FCPCA_URL"; then
  echo "Could not fetch the FCPCA G2 root from $FCPCA_URL — check network and re-run." >&2
  exit 1
fi
openssl x509 -inform DER -in fcpca.crt -out fcpca.pem 2>/dev/null \
  || openssl x509 -in fcpca.crt -out fcpca.pem 2>/dev/null \
  || { echo "Fetched FCPCA file is not a certificate." >&2; exit 1; }
import_cert fcpca.pem

urls=$(sia_urls fcpca.pem)
[ -n "$urls" ] || urls="$FCPCA_SIA_FALLBACK"
for u in $urls; do process_bundle "$u" 0; done
for u in $EXTRA_SIA_SEEDS; do process_bundle "$u" 1; done

echo "Federal PKI import complete ($(wc -l < "$seen") certs processed into $DB)."
FEDEOF
chmod +x ~/.local/bin/import-federal-cas.sh

#
# DoD PKI — import the complete official CA bundle into the per-user NSS db
#
cat > ~/.local/bin/import-dod-cas.sh <<'DODEOF'
#!/usr/bin/env bash
set -uo pipefail
DB="sql:$HOME/.pki/nssdb"
DOD_ZIP_URL="https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/unclass-certificates_pkcs7_DoD.zip"

for t in certutil openssl curl unzip; do
  command -v "$t" >/dev/null 2>&1 || { echo "Missing $t — layer nss-tools/openssl/curl/unzip with rpm-ostree and reboot, then re-run." >&2; exit 1; }
done

[ -f "$HOME/.pki/nssdb/cert9.db" ] || { mkdir -p "$HOME/.pki/nssdb"; certutil -d "$DB" -N --empty-password; }

work=$(mktemp -d); trap 'rm -rf "$work"' EXIT; cd "$work" || exit 1

echo "Fetching DoD PKI CA bundle ..."
curl -fsSL --max-time 60 -o dod.zip "$DOD_ZIP_URL" || { echo "DoD bundle download failed." >&2; exit 1; }
unzip -qj dod.zip -d bundle || { echo "DoD bundle unzip failed." >&2; exit 1; }

shopt -s nullglob nocaseglob
p7b=""
for f in bundle/*dod*pem*.p7b; do p7b="$f"; break; done
if [ -z "$p7b" ]; then for f in bundle/*dod*.p7b; do p7b="$f"; break; done; fi
shopt -u nullglob nocaseglob
[ -n "$p7b" ] || { echo "No DoD .p7b found in bundle (naming changed?) — inspect the zip manually." >&2; exit 1; }
echo "Using bundle file: $(basename "$p7b")"

openssl pkcs7 -print_certs -in "$p7b" >certs.pem 2>/dev/null \
  || openssl pkcs7 -print_certs -inform DER -in "$p7b" >certs.pem 2>/dev/null \
  || { echo "Could not parse $p7b as PKCS#7." >&2; exit 1; }
awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("seg" n ".pem")}' certs.pem

roots=0; inters=0
for c in seg*.pem; do
  [ -s "$c" ] || continue
  openssl x509 -in "$c" -noout >/dev/null 2>&1 || continue
  subj=$(openssl x509 -in "$c" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$c" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  fp=$(openssl x509 -in "$c" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
  short=$(echo "$subj" | grep -oiE 'CN=[^,]+' | head -1 | cut -d= -f2-)
  nick="${short:-DoD CA} ${fp:0:8}"
  if [ "$subj" = "$iss" ]; then
    certutil -d "$DB" -A -n "$nick" -t "CT,C,C" -i "$c" 2>/dev/null && { echo "  trusted root : $nick"; roots=$((roots+1)); }
  else
    certutil -d "$DB" -A -n "$nick" -t ",,"    -i "$c" 2>/dev/null && { echo "  intermediate : $nick"; inters=$((inters+1)); }
  fi
done
echo "DoD PKI import complete: $roots roots trusted, $inters intermediates added to $DB."
DODEOF
chmod +x ~/.local/bin/import-dod-cas.sh

#
# Fleet verification + card diagnostics
#
cat > ~/.local/bin/verify-pki-trust.sh <<'VERIFYEOF'
#!/usr/bin/env bash
#
# verify-pki-trust.sh [path/to/piv-auth-leaf.pem]
#
# Card-free verification that a machine can validate USDA PIV and DoD chains.
# Exit code 0 = all checks pass, nonzero = something failed.
#
set -uo pipefail

DB_DIR="$HOME/.pki/nssdb"
DB="sql:$DB_DIR"
SSP_AIA_URL="http://sspweb.managed.entrust.com/AIA/CertsIssuedToEMSSSPCA.p7c"
LEAF="${1:-}"

pass=0; fail=0
ok()  { printf '  [PASS] %s\n' "$*"; pass=$((pass+1)); }
bad() { printf '  [FAIL] %s\n' "$*"; fail=$((fail+1)); }
info(){ printf '  [ -- ] %s\n' "$*"; }
hr()  { printf -- '---------------------------------------------------------------\n'; }

for t in certutil openssl curl; do
  command -v "$t" >/dev/null 2>&1 || { echo "Missing $t — layer nss-tools/openssl/curl with rpm-ostree and reboot, then re-run."; exit 2; }
done

work=$(mktemp -d); trap 'rm -rf "$work"' EXIT

validate_file() {
  local f="$1" usage="$2"
  if command -v vfychain >/dev/null 2>&1; then
    local u; case "$usage" in C) u=0 ;; L) u=3 ;; *) u="$usage" ;; esac
    vfychain -d "$DB" -u "$u" -a "$f" >/dev/null 2>&1
    return $?
  fi
  local nick rc=1 fp cfp line trustcol cand existing=""
  nick="__verify_tmp_$$_${RANDOM}"
  certutil -d "$DB" -A -n "$nick" -t ",," -i "$f" 2>/dev/null || return 1
  if certutil -d "$DB" -L -n "$nick" >/dev/null 2>&1; then
    certutil -d "$DB" -V -u "$usage" -n "$nick" </dev/null >/dev/null 2>&1 && rc=0
    certutil -d "$DB" -D -n "$nick" 2>/dev/null
  else
    fp=$(openssl x509 -in "$f" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
    while IFS= read -r line; do
      line="${line%"${line##*[![:space:]]}"}"
      trustcol=${line##* }; cand=${line%"$trustcol"}
      cand="${cand%"${cand##*[![:space:]]}"}"
      [ -n "$cand" ] || continue
      cfp=$(certutil -d "$DB" -L -n "$cand" -a 2>/dev/null \
              | openssl x509 -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
      [ "$cfp" = "$fp" ] && { existing="$cand"; break; }
    done < <(certutil -d "$DB" -L 2>/dev/null | tail -n +5)
    if [ -n "$existing" ]; then
      certutil -d "$DB" -V -u "$usage" -n "$existing" </dev/null >/dev/null 2>&1 && rc=0
    fi
  fi
  return "$rc"
}

hr; echo "PKI trust verification — $(hostname) — $DB"

if [ -f "$DB_DIR/cert9.db" ]; then
  ok "nssdb exists"
else
  bad "no nssdb at $DB_DIR — PKI imports have not run for this user"
  hr; echo "RESULT: FAILED ($fail failure(s))"; exit 1
fi

nsslist=$(certutil -d "$DB" -L 2>/dev/null | tail -n +5)

fcp_line=$(echo "$nsslist" | grep -i 'federal common policy' | head -1 || true)
if [ -n "$fcp_line" ] && echo "$fcp_line" | awk '{print $NF}' | grep -qE '[CT]'; then
  ok "Federal Common Policy CA G2 present and trusted"
elif [ -n "$fcp_line" ]; then
  bad "FCPCA G2 present but NOT trusted (trust: $(echo "$fcp_line" | awk '{print $NF}')) — re-run import-federal-cas.sh"
else
  bad "FCPCA G2 not in nssdb — run import-federal-cas.sh"
fi

if echo "$nsslist" | grep -qi 'entrust managed services ssp'; then
  ok "Entrust Managed Services SSP CA (USDA issuer) present"
else
  bad "Entrust Managed Services SSP CA not in nssdb — run import-federal-cas.sh"
fi

if curl -fsS --max-time 25 -o "$work/ssp.p7c" "$SSP_AIA_URL"; then
  if openssl pkcs7 -inform DER -in "$work/ssp.p7c" -print_certs 2>/dev/null >"$work/ssp_all.pem" \
     || openssl pkcs7 -in "$work/ssp.p7c" -print_certs 2>/dev/null >"$work/ssp_all.pem"; then
    awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("'"$work"'/ssp" n ".pem")}' "$work/ssp_all.pem"
    live_ok=0; diag_cert=""
    for c in "$work"/ssp[0-9]*.pem; do
      [ -s "$c" ] || continue
      openssl x509 -in "$c" -noout 2>/dev/null || continue
      if validate_file "$c" L; then live_ok=1; break; fi
      diag_cert="$c"
    done
    if [ "$live_ok" -eq 1 ]; then
      ok "LIVE: real Entrust SSP CA cert validates as SSL CA against this trust store"
    else
      bad "LIVE: fetched SSP CA cert does NOT validate — chain to a trust anchor is broken here"
      if [ -n "$diag_cert" ]; then
        info "       candidate: $(openssl x509 -in "$diag_cert" -noout -subject -nameopt RFC2253 2>/dev/null | sed 's/^subject=//')"
        info "       validity : $(openssl x509 -in "$diag_cert" -noout -enddate 2>/dev/null | cut -d= -f2)"
        if command -v vfychain >/dev/null 2>&1; then
          vfychain -d "$DB" -u 3 -a "$diag_cert" 2>&1 | grep -E 'ERROR|CERT [0-9]' | head -4 \
            | while IFS= read -r l; do info "       NSS: $l"; done
        else
          info "       (inspect further with: certutil -d $DB -V -u L -n '<its nickname>')"
        fi
      fi
    fi
  else
    info "LIVE check skipped: could not parse the fetched AIA bundle"
  fi
else
  info "LIVE check skipped: could not reach $SSP_AIA_URL (offline?) — static checks above still stand"
fi

dod_total=$(echo "$nsslist" | grep -ci 'dod root ca' || true)
dod_trusted=$(echo "$nsslist" | grep -i 'dod root ca' | awk '{print $NF}' | grep -cE '[CT]' || true)
if [ "${dod_trusted:-0}" -ge 1 ]; then
  ok "DoD Root CAs: $dod_trusted trusted (of $dod_total present)"
else
  bad "No trusted DoD Root CAs in nssdb — run import-dod-cas.sh"
fi

if [ -z "$LEAF" ] && command -v pkcs11-tool >/dev/null 2>&1 \
   && opensc-tool -l 2>/dev/null | grep -q 'Yes'; then
  if pkcs11-tool --read-object --type cert --id 1 2>/dev/null \
       | openssl x509 -inform DER -out "$work/card-leaf.pem" 2>/dev/null; then
    LEAF="$work/card-leaf.pem"
    info "Gold-standard leaf read live from the inserted PIV card."
  fi
fi
if [ -n "$LEAF" ]; then
  if [ ! -f "$LEAF" ]; then
    bad "leaf file not found: $LEAF"
  elif ! openssl x509 -in "$LEAF" -noout 2>/dev/null; then
    bad "leaf file is not a PEM certificate: $LEAF (export with the pkcs11-tool one-liner in the header)"
  elif validate_file "$LEAF" C; then
    ok "GOLD: your PIV Authentication leaf validates for TLS CLIENT AUTH on this host"
  else
    bad "GOLD: your leaf does NOT validate here — a chain link is missing on this host"
  fi
else
  info "No leaf supplied and no PIV card inserted — gold-standard check skipped."
  info "(Optional: export the public leaf on the card host with"
  info "  pkcs11-tool --read-object --type cert --id 1 | openssl x509 -inform DER -out ~/piv-auth-leaf.pem"
  info " and pass its path as \$1 on other hosts.)"
fi

hr
if [ "$fail" -eq 0 ]; then
  echo "RESULT: OK — $pass check(s) passed. This host will offer PIV certs and trust DoD chains."
  exit 0
else
  echo "RESULT: FAILED — $fail failure(s), $pass pass(es). See FAIL lines above."
  exit 1
fi
VERIFYEOF
chmod +x ~/.local/bin/verify-pki-trust.sh

cat > ~/.local/bin/piv-card-recon.sh <<'RECONEOF'
#!/usr/bin/env bash
#
# piv-card-recon.sh — READ-ONLY reconnaissance of a PIV card and the local
# trust state. Changes NOTHING: no imports, no config writes.
#
set -uo pipefail

DB="sql:$HOME/.pki/nssdb"
ok()   { printf '  [ OK ] %s\n' "$*"; }
bad()  { printf '  [FAIL] %s\n' "$*"; }
info() { printf '  [ -- ] %s\n' "$*"; }
hr()   { printf -- '---------------------------------------------------------------\n'; }

hr; echo "0. Tooling"
missing=0
for t in pkcs11-tool opensc-tool openssl curl certutil p11-kit; do
  if command -v "$t" >/dev/null 2>&1; then ok "$t $(command -v "$t")"
  else bad "$t missing"; missing=1; fi
done
[ "$missing" -eq 1 ] && { echo; echo "Layer missing tools (rpm-ostree install opensc nss-tools openssl p11-kit) and reboot, then re-run."; exit 1; }

hr; echo "1. Smartcard stack"
if systemctl is-active --quiet pcscd 2>/dev/null || systemctl is-active --quiet pcscd.socket 2>/dev/null; then
  ok "pcscd is active (service or socket)"
else
  info "pcscd not currently active (socket activation may start it on demand)"
fi

readers=$(opensc-tool -l 2>/dev/null || true)
if [ -z "$readers" ] || echo "$readers" | grep -qi 'No smart card readers'; then
  bad "No smartcard reader detected. Plug in the reader and re-run."
  exit 1
fi
echo "$readers" | sed 's/^/       /'
if echo "$readers" | grep -q 'Yes'; then
  ok "Card present in reader"
else
  bad "Reader present but NO card detected. Insert the PIV card and re-run."
  exit 1
fi
card_name=$(opensc-tool -n 2>/dev/null || echo "unknown")
info "Card recognized as: $card_name"

if p11-kit list-modules 2>/dev/null | grep -qi 'opensc'; then
  ok "OpenSC PKCS#11 module registered with p11-kit (browsers will see the card)"
else
  bad "OpenSC module NOT visible to p11-kit — browsers won't see the card. Check the opensc package."
fi

hr; echo "2. Certificates on the card"
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT

mapfile -t cert_ids < <(pkcs11-tool --list-objects --type cert 2>/dev/null \
  | grep -oE 'ID:[[:space:]]*[0-9a-fA-F]+' | awk '{print $2}' | sort -u)
if [ "${#cert_ids[@]}" -eq 0 ]; then
  bad "pkcs11-tool sees no certificate objects on the card."
  exit 1
fi

leaf=""
for id in "${cert_ids[@]}"; do
  der="$work/card_$id.der"; pem="$work/card_$id.pem"
  pkcs11-tool --read-object --type cert --id "$id" >"$der" 2>/dev/null || continue
  openssl x509 -inform DER -in "$der" -out "$pem" 2>/dev/null || continue
  subj=$(openssl x509 -in "$pem" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$pem" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  na=$(openssl x509 -in "$pem" -noout -enddate 2>/dev/null | cut -d= -f2)
  eku=$(openssl x509 -in "$pem" -noout -ext extendedKeyUsage 2>/dev/null | tail -n +2 | tr -d ' ' | tr '\n' ' ')
  echo "  slot id $id:"
  echo "     subject : $subj"
  echo "     issuer  : $iss"
  echo "     expires : $na"
  [ -n "$eku" ] && echo "     EKU     : $eku"
  if openssl x509 -in "$pem" -checkend 0 >/dev/null 2>&1; then :; else bad "  slot $id cert is EXPIRED"; fi
  case "$id" in 01|1) leaf="$pem" ;; esac
done
if [ -z "$leaf" ]; then
  bad "No PIV Authentication cert (object id 01) found — chain walk skipped."
  exit 1
fi

leaf_iss=$(openssl x509 -in "$leaf" -noout -issuer -nameopt RFC2253 2>/dev/null); leaf_iss=${leaf_iss#issuer=}
suggest_org=$(echo "$leaf_iss" | grep -oE 'O=[^,]+' | head -1 | cut -d= -f2-)

hr; echo "3. Local trust store ($DB)"
declare -A NSS_TRUST=()
if [ -f "$HOME/.pki/nssdb/cert9.db" ]; then
  while IFS= read -r line; do
    line="${line%"${line##*[![:space:]]}"}"
    trust=${line##* }; nick=${line%"$trust"}
    nick="${nick%"${nick##*[![:space:]]}"}"
    [ -n "$nick" ] || continue
    pemtmp="$work/nss_one.pem"
    certutil -d "$DB" -L -n "$nick" -a >"$pemtmp" 2>/dev/null || continue
    awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("'"$work"'/nsseg" n ".pem")}' "$pemtmp"
    for f in "$work"/nsseg*.pem; do
      [ -s "$f" ] || continue
      fp=$(openssl x509 -in "$f" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
      [ -n "$fp" ] && NSS_TRUST["$fp"]="$trust"
      rm -f "$f"
    done
  done < <(certutil -d "$DB" -L 2>/dev/null | tail -n +5)
  echo "  nssdb exists with ${#NSS_TRUST[@]} certificate(s) loaded."
else
  info "No ~/.pki/nssdb yet (no browser has created one and no import has run)."
fi

nss_status() {
  local fp t
  fp=$(openssl x509 -in "$1" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
  t="${NSS_TRUST[$fp]:-}"
  if [ -z "$t" ]; then echo "MISSING from nssdb"
  elif [[ "$t" == *C* ]] || [[ "$t" == *T* ]]; then echo "present, TRUSTED ($t)"
  else echo "present, chain-only ($t)"; fi
}

hr; echo "4. Chain the PIV Authentication cert requires (leaf -> root)"
ski() { openssl x509 -in "$1" -noout -text 2>/dev/null | grep -A1 "Subject Key Identifier"   | tail -1 | tr -d ' '; }
aki() { openssl x509 -in "$1" -noout -text 2>/dev/null | grep -A1 "Authority Key Identifier" | tail -1 | tr -d ' ' | sed 's/keyid://'; }

hop=0
cur="$leaf"
subj=$(openssl x509 -in "$cur" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
echo "  [$hop] LEAF: $subj"
echo "        (leaf lives on the card; it is never imported anywhere)"

while :; do
  hop=$((hop+1)); [ "$hop" -gt 8 ] && { bad "chain longer than 8 hops? stopping."; break; }
  subj=$(openssl x509 -in "$cur" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$cur" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  [ "$subj" = "$iss" ] && break
  want=$(aki "$cur")
  mapfile -t aia_urls < <(openssl x509 -in "$cur" -noout -text 2>/dev/null \
      | grep -oE 'CA Issuers - URI:https?://[^ ]+' | sed 's/CA Issuers - URI://')
  if [ "${#aia_urls[@]}" -eq 0 ]; then
    bad "  [$hop] cert has NO AIA caIssuers URL — chain cannot be auto-discovered above: $subj"
    break
  fi
  parent=""
  for u in "${aia_urls[@]}"; do
    tmp="$work/aia.bin"
    curl -fsS --max-time 20 -o "$tmp" "$u" || { info "  [$hop] AIA fetch failed: $u"; continue; }
    certs="$work/aia.pem"
    openssl pkcs7 -inform DER -in "$tmp" -print_certs 2>/dev/null >"$certs" \
      || openssl pkcs7 -in "$tmp" -print_certs 2>/dev/null >"$certs" \
      || openssl x509 -inform DER -in "$tmp" 2>/dev/null >"$certs" || continue
    rm -f "$work"/aiaseg*.pem
    awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("'"$work"'/aiaseg" n ".pem")}' "$certs"
    best=""; best_root=""
    for c in "$work"/aiaseg*.pem; do
      [ -s "$c" ] || continue
      openssl x509 -in "$c" -noout >/dev/null 2>&1 || continue
      csub=$(openssl x509 -in "$c" -noout -subject -nameopt RFC2253 2>/dev/null); csub=${csub#subject=}
      ciss=$(openssl x509 -in "$c" -noout -issuer  -nameopt RFC2253 2>/dev/null); ciss=${ciss#issuer=}
      if { [ -n "$want" ] && [ "$(ski "$c")" = "$want" ]; } \
         || { [ -z "$want" ] && [ "$csub" = "$iss" ]; }; then
        if [ "$csub" = "$ciss" ]; then best_root="$c"; else best="$c"; fi
      fi
    done
    parent="${best_root:-$best}"
    if [ -n "$parent" ]; then
      psub=$(openssl x509 -in "$parent" -noout -subject -nameopt RFC2253 2>/dev/null); psub=${psub#subject=}
      pkind="intermediate"; [ "$best_root" = "$parent" ] && pkind="SELF-SIGNED ROOT"
      echo "  [$hop] $pkind: $psub"
      echo "        found via  : $u"
      echo "        nssdb state: $(nss_status "$parent")"
      cp "$parent" "$work/hop$hop.pem"; cur="$work/hop$hop.pem"
      break
    fi
  done
  [ -n "$parent" ] || { bad "  [$hop] no parent matching AKI found in any AIA bundle for: $subj"; break; }
done

hr; echo "5. Recommendations"
echo "  Leaf issuer          : $leaf_iss"
echo "  Suggested BRANCH_FILTER for import-federal-cas.sh: '${suggest_org:-<none found>}'"
echo "    (compare against the current value; it matches case-insensitively on the CA subject)"
echo
if certutil -d "$DB" -V -u C -n "PIV_II:Certificate for PIV Authentication" </dev/null 2>/dev/null; then
  ok "certutil validates the card's PIV Authentication cert for TLS client auth NOW."
  echo "       Browsers should offer the cert. If a site still doesn't prompt, it's server-side."
else
  info "certutil could not validate the token cert (missing chain links above, or a"
  info "different token label). If any hop shows MISSING, run: import-federal-cas.sh"
  info "then import-piv-cas.sh (card inserted), and re-run this recon."
fi
hr
echo "Recon complete. Nothing was modified. Paste this output back for analysis."
RECONEOF
chmod +x ~/.local/bin/piv-card-recon.sh

# Run card-free PKI imports now (non-fatal). These need certutil (nss-tools),
# which was layered in the main rpm-ostree call. If --apply-live didn't stick,
# defer to after reboot rather than triggering another rpm-ostree transaction.
if command -v certutil &>/dev/null; then
  ~/.local/bin/import-federal-cas.sh \
    || echo "WARN: Federal/USDA PKI import failed — run import-federal-cas.sh manually."
  ~/.local/bin/import-dod-cas.sh \
    || echo "WARN: DoD PKI import failed — run import-dod-cas.sh manually."

  if opensc-tool -l 2>/dev/null | grep -q 'Yes'; then
    ~/.local/bin/import-piv-cas.sh || echo "WARN: PIV CA import failed; run import-piv-cas.sh manually with the card inserted."
  else
    echo "No PIV card detected (fine — Federal chain already imported card-free above)."
  fi

  ~/.local/bin/verify-pki-trust.sh \
    || echo "WARN: PKI self-check reported failures above — fix and re-run verify-pki-trust.sh."
else
  echo "WARN: certutil not available yet (reboot needed for layered packages)."
  echo "      After reboot, run: import-federal-cas.sh && import-dod-cas.sh && verify-pki-trust.sh"
fi

#
# Fonts / desktop tweaks (gsettings work the same on Bazzite GNOME)
#
gsettings set org.gnome.desktop.interface font-hinting 'slight'
gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
gsettings set org.gnome.desktop.interface font-name 'Inter Variable 11'
gsettings set org.gnome.desktop.interface document-font-name 'Inter Variable 12'
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste true
gsettings set org.gnome.nautilus.preferences date-time-format 'detailed'

gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.interface clock-show-weekday true
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface color-scheme 'default'
gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'
gsettings set org.gnome.mutter center-new-windows true
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true

#
# Signal update timer (AppImage needs its own updater; Flatpak apps auto-update)
#
mkdir -p ~/.config/systemd/user
cat > ~/.config/systemd/user/update-signal.service <<'EOF'
[Unit]
Description=Update Signal Desktop AppImage

[Service]
Type=oneshot
ExecStart=%h/.local/bin/update-signal-appimage.sh
EOF

cat > ~/.config/systemd/user/update-signal.timer <<'EOF'
[Unit]
Description=Weekly Signal AppImage update check

[Timer]
OnCalendar=weekly
Persistent=true
RandomizedDelaySec=2h

[Install]
WantedBy=timers.target
EOF
systemctl --user daemon-reload
systemctl --user enable --now update-signal.timer

#
# Fingerprint authentication — detect a fingerprint scanner, layer fprintd,
# enable the PAM module via authselect, and walk the user through enrollment.
#
if command -v fprintd-list &>/dev/null && fprintd-list "$USER" 2>/dev/null | grep -q 'found [1-9]'; then
  echo
  echo "======================================================================="
  echo " Fingerprint scanner detected."
  echo "======================================================================="

  if authselect current --raw 2>/dev/null | grep -q 'with-fingerprint'; then
    echo "authselect: with-fingerprint already enabled."
  else
    active_profile=$(authselect current --raw 2>/dev/null | awk '{print $1}')
    active_profile="${active_profile:-sssd}"
    sudo authselect enable-feature with-fingerprint
    echo "authselect: enabled with-fingerprint on the '$active_profile' profile."
  fi

  if fprintd-list "$USER" 2>/dev/null | grep -qE '^\s+-\s+#[0-9]+:'; then
    echo "Fingerprint(s) already enrolled for $USER — skipping enrollment."
  else
    echo
    echo "No fingerprints enrolled yet. You can enroll your right index finger now."
    echo "You will need to swipe/press several times when prompted."
    echo
    read -rp "Enroll a fingerprint now? [Y/n] " fp_answer
    case "${fp_answer,,}" in
      n|no)
        echo "Skipped. Enroll later with:  fprintd-enroll"
        ;;
      *)
        fprintd-enroll -f right-index-finger || {
          echo "WARN: enrollment failed or was cancelled. Enroll later with:  fprintd-enroll"
        }
        ;;
    esac
  fi
else
  echo "No fingerprint scanner detected — skipping fingerprint auth setup."
fi

echo
echo "Done. Log out/in (or reboot) for shell extensions and layered packages to fully apply."
echo "YubiKey: lock-on-removal and wake-on-insert are active (udev rules loaded)."
echo "         FIDO2/PAM enrollment steps are listed in the YubiKey section comments."
echo "PKI:     Federal/USDA and DoD CA bundles imported to ~/.pki/nssdb (no card"
echo "         needed) and self-checked above. On PATH for any host/user:"
echo "         verify-pki-trust.sh (fleet PASS/FAIL) and piv-card-recon.sh (deep"
echo "         diagnostics with the card inserted)."
if command -v fprintd-list &>/dev/null \
   && fprintd-list "$USER" 2>/dev/null | grep -qE '^\s+-\s+#[0-9]+:'; then
  echo "Fingerprint: enrolled and active for login, sudo, and screen unlock."
  echo "             Re-enroll / add fingers with:  fprintd-enroll"
fi
