#!/usr/bin/env bash
#
# Fedora 44 post-install setup (dnf5)
# RPM-first. No snaps, no flatpaks (Signal uses the official AppImage).
#
# Usage (fresh install): clone or download this ONE file and run it as your
# normal user. Don't pipe it to bash from curl — download, read, run:
#   curl -fLO https://raw.githubusercontent.com/<you>/<repo>/main/fedora_stuff.sh
#   chmod +x fedora_stuff.sh && ./fedora_stuff.sh
# Everything else (updaters, PKI importers, verifiers) is generated by this
# script into ~/.local/bin and /usr/local/sbin — nothing else to check out.
#
# Package installs are batched into as few dnf transactions as possible so
# metadata is fetched once and dependencies resolve once. dnf can only "see" a
# repo after its -release package is installed, which forces the staging below:
#   dnf #1  RPMFusion free/nonfree + plugins-core  -> enables the rpmfusion repos
#   dnf #2  RPMFusion tainted releases             -> live in the repos from #1
#   dnf #3  one big install                        -> groups + codecs + apps +
#                                                     fonts (incl. libdvdcss,
#                                                     which needs the tainted repo)
#   dnf #4  remove nano                            -> install+remove can't share a txn
#
set -euo pipefail

#
# Run as your normal user, NOT with sudo. The script calls sudo only on the
# lines that need root; running the whole thing as root would drop Signal, its
# launcher/icon, and all the per-user gsettings into /root instead of your home.
#
if [ "$EUID" -eq 0 ]; then
  echo "Don't run this with sudo / as root. Run it as your normal user:" >&2
  echo "    ./fedora_stuff.sh" >&2
  echo "It will prompt for your password when it reaches the first sudo step." >&2
  exit 1
fi

#
# This script configures per-user GNOME settings via gsettings, which need a
# running D-Bus session bus. Bail out early if there isn't one (e.g. invoked
# over SSH or from a bare TTY) rather than failing cryptically mid-run.
#
if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
  echo "No D-Bus session bus found (DBUS_SESSION_BUS_ADDRESS is unset)." >&2
  echo "This script sets GNOME preferences with gsettings and must run inside a" >&2
  echo "graphical GNOME session — not over SSH or a plain TTY. Log in to the" >&2
  echo "desktop, open a terminal there, and re-run it." >&2
  exit 1
fi

#
# DNF tuning
#
grep -q '^max_parallel_downloads' /etc/dnf/dnf.conf || \
  echo 'max_parallel_downloads=10' | sudo tee -a /etc/dnf/dnf.conf > /dev/null

#
# Third-party repos (key + repo files only — no dnf yet)
#
# Microsoft signing key (shared by VS Code + Edge)
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc

# VS Code repo
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | \
  sudo tee /etc/yum.repos.d/vscode.repo > /dev/null

# Microsoft Edge repo (proper Fedora-side repo, not the SLES packages-microsoft-prod hack)
echo -e "[microsoft-edge]\nname=microsoft-edge\nbaseurl=https://packages.microsoft.com/yumrepos/edge\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | \
  sudo tee /etc/yum.repos.d/microsoft-edge.repo > /dev/null

#
# dnf #1 — RPMFusion (free + nonfree) + plugins-core.
# These -release packages enable the rpmfusion repos for everything below.
#
sudo dnf -y install \
  "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
  "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm" \
  dnf-plugins-core

#
# dnf #2 — RPMFusion tainted releases.
# Must be its own transaction: the tainted -release packages live in the
# rpmfusion repos that only became available after dnf #1. libdvdcss (installed
# in dnf #3) in turn lives in the tainted repo these enable.
#
sudo dnf -y install rpmfusion-free-release-tainted rpmfusion-nonfree-release-tainted

#
# Bring the system fully up to date before the big install.
# IMPORTANT: if this pulls a NEW KERNEL and you have an NVIDIA GPU, reboot
# before re-running the script so that akmod-nvidia builds its module against
# the running kernel and not one that hasn't been booted yet.
#
sudo dnf -y update

#
# dnf #3 — the big one. Comps groups + the full (non-free/tainted) codec set +
# every application + fonts, in a single transaction.
#
# Detect GPU vendor(s) for driver/VA-API selection. Match PCI vendor IDs from
# lspci -nn ([10de]=NVIDIA, [8086]=Intel, [1002]/[1022]=AMD/ATI), NOT name
# strings — 'ati' as a substring matches "Corporation", which appears in nearly
# every lspci line. Each vendor is checked independently (no elif): hybrid
# laptops (e.g. Intel iGPU + NVIDIA dGPU) have more than one GPU, and the iGPU
# usually renders the desktop and decodes video, so it needs its VA-API driver
# alongside the NVIDIA stack.
gpu_lines=$(lspci -nn 2>/dev/null | grep -iE 'vga|3d|display' || true)
nvidia_pkgs=()
vaapi_pkgs=()
if grep -q '\[10de:' <<< "$gpu_lines"; then
  nvidia_pkgs=(akmod-nvidia xorg-x11-drv-nvidia-cuda libva-nvidia-driver)
  echo "NVIDIA GPU detected — will install proprietary driver + CUDA + VA-API."
fi
if grep -q '\[8086:' <<< "$gpu_lines"; then
  vaapi_pkgs+=(intel-media-driver)
  echo "Intel GPU detected — will install intel-media-driver for VA-API."
fi
if grep -qE '\[10(02|22):' <<< "$gpu_lines"; then
  vaapi_pkgs+=(mesa-va-drivers-freeworld)
  echo "AMD GPU detected — will install mesa-va-drivers-freeworld for VA-API."
fi
if [ ${#nvidia_pkgs[@]} -eq 0 ] && [ ${#vaapi_pkgs[@]} -eq 0 ]; then
  echo "No recognized GPU vendor detected — skipping GPU-specific packages."
fi

# Resolve Ferdium's latest x86_64 RPM URL up front so it can ride along in the
# same dnf call. Skip if already installed (also avoids needless GitHub API hits).
ferdium_pkg=()
if rpm -q ferdium &>/dev/null; then
  echo "Ferdium already installed, skipping its download."
else
  FERDIUM_RPM=$(curl -fsSL https://api.github.com/repos/ferdium/ferdium-app/releases/latest \
    | python3 -c 'import json, sys
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for a in d.get("assets", []):
    if a["name"].endswith("x86_64.rpm"):
        print(a["browser_download_url"]); break' || true)
  if [ -n "$FERDIUM_RPM" ]; then
    ferdium_pkg=("$FERDIUM_RPM")
  else
    echo "WARN: could not resolve Ferdium RPM URL (GitHub API down/rate-limited?), skipping."
  fi
fi

# Notes:
#  - Groups are *installed* (not just upgraded); weak deps are on by default, so
#    the full codec set comes along. The explicit gstreamer1-* lines guarantee
#    the non-free/freeworld plugins land regardless of group contents.
#  - ffmpeg + --allowerasing swaps out Fedora's ffmpeg-free automatically.
#  - libdvdcss comes from the tainted repo enabled in dnf #2.
#  - GPU driver/VA-API packages are selected dynamically by PCI vendor ID:
#    NVIDIA → akmod-nvidia + cuda + libva-nvidia-driver (see kernel/reboot note),
#    Intel → intel-media-driver, AMD → mesa-va-drivers-freeworld. Checks are
#    independent, so hybrid iGPU+dGPU machines get all applicable drivers.
#  - No \*-firmware glob: the base install already provides your hardware's
#    firmware and keeps it current via linux-firmware/kernel updates + fwupd.
#  - YubiKey set: ydotool drives the udev wake-on-insert rule; pcsc-lite/ccid
#    provide smartcard (PIV / GPG) access; pam-u2f + pamu2fcfg enable FIDO2 PAM
#    auth (enrollment is manual — see the YubiKey section); yubikey-manager
#    (ykman) configures the key itself.
#  - PIV/PKI set: opensc is the PKCS#11 module that reads PIV/CAC cards (and
#    p11-kit auto-registers it for every browser — see the PIV section);
#    nss-tools provides certutil for the CA imports; openssl/gnupg2/unzip
#    support the cert-chain and DoD-bundle helpers.
#  - vim-default-editor needs --allowerasing to displace nano-default-editor.
sudo dnf -y install --allowerasing \
  --exclude=PackageKit-gstreamer-plugin \
  @core @multimedia @sound-and-video \
  ffmpeg libavcodec-freeworld \
  gstreamer1-plugins-ugly gstreamer1-plugins-bad-freeworld gstreamer1-libav \
  libdvdcss \
  "${nvidia_pkgs[@]}" "${vaapi_pkgs[@]}" \
  gnome-shell-extension-common gnome-shell-extension-user-theme \
  gnome-shell-extension-freon gnome-shell-extension-no-overview \
  gnome-shell-extension-dash-to-dock \
  gnome-shell-extension-appindicator gnome-shell-extension-caffeine \
  gnome-shell-extension-blur-my-shell gnome-shell-extension-just-perfection \
  microsoft-edge-stable code \
  https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm \
  steam \
  gnome-tweaks gnome-extensions-app dconf-editor git btop fastfetch solaar \
  mpv vlc yt-dlp 7zip unrar \
  rsms-inter-vf-fonts \
  fuse-libs \
  ydotool pcsc-lite pcsc-lite-ccid pam-u2f pamu2fcfg yubikey-manager \
  opensc nss-tools openssl gnupg2 unzip \
  vim-default-editor \
  "${ferdium_pkg[@]}"

# Hardware-accelerated video decode: GPU-specific VA-API driver is selected
# automatically above based on lspci output and installed in dnf #3.

#
# Enable GNOME shell extensions at startup.
# Installing the RPM only drops files in /usr/share/gnome-shell/extensions;
# they still have to be added to org.gnome.shell enabled-extensions. We write
# the gsettings key directly so it works even before the shell has rescanned
# (gnome-extensions enable would refuse until then) and survives a re-login.
#
gext_enable() {
  local uuid="$1" cur new
  # 1. Make sure the UUID is in enabled-extensions (append if missing).
  cur=$(gsettings get org.gnome.shell enabled-extensions)
  case "$cur" in
    *"'$uuid'"*)     ;;                                            # already enabled
    "@as []"|"[]")   gsettings set org.gnome.shell enabled-extensions "['$uuid']" ;;
    *)               gsettings set org.gnome.shell enabled-extensions "${cur%]}, '$uuid']" ;;
  esac
  # 2. On GNOME 46+ a UUID left in disabled-extensions overrides enabled-extensions
  #    and the extension stays off. Strip it out of the disabled list if present.
  cur=$(gsettings get org.gnome.shell disabled-extensions)
  if [[ "$cur" == *"'$uuid'"* ]]; then
    new=$(python3 -c 'import ast, sys
v, u = sys.argv[1], sys.argv[2]
lst = ast.literal_eval(v) if v.lstrip().startswith("[") else []
print("[" + ", ".join(repr(x) for x in lst if x != u) + "]")' "$cur" "$uuid")
    gsettings set org.gnome.shell disabled-extensions "$new"
  fi
}
gext_enable dash-to-dock@micxgx.gmail.com
gext_enable no-overview@fthx
gext_enable appindicatorsupport@rgcjonas.gmail.com   # tray icons (Signal, Ferdium, etc.)
gext_enable caffeine@patapon.info
gext_enable blur-my-shell@aunetx
gext_enable just-perfection-desktop@just-perfection

#
# Signal Desktop — official AppImage (GPG-verified). No flatpak needed.
#
# Signal Desktop's release-signing key. The key is imported into the default gpg
# keyring, but signature verification is BOUND to this fingerprint via gpg's
# VALIDSIG status line (see update-signal-appimage.sh below), so extra/unexpected
# keys in the keyring cannot pass verification — only a signature made by this
# key (or a subkey of it) is accepted. Source (official):
#   https://updates.signal.org/static/desktop/appimage.asc
#   uid: Signal Messenger, LLC <support@signal.org>
SIGNAL_KEY_FPR="4B16B7232DFAA439AD791002EF9F501F13EED94C"

# Import Signal's signing key. The presence check below is only a fast-fail
# convenience: it aborts early with a clear message if the import didn't yield
# the expected key. The real security enforcement is the VALIDSIG fingerprint
# match at verify time in the updater. gpg --import is a no-op if already present.
curl -fsSL https://updates.signal.org/static/desktop/appimage.asc | gpg --import
if ! gpg --with-colons --fingerprint "$SIGNAL_KEY_FPR" 2>/dev/null \
     | grep -q "^fpr:::::::::${SIGNAL_KEY_FPR}:"; then
  echo "ERROR: Signal signing key $SIGNAL_KEY_FPR not present after import." >&2
  echo "Aborting before download." >&2
  exit 1
fi

# The weekly updater is the single code path that downloads, GPG-verifies, and
# atomically installs the AppImage (curl -fL, fingerprint-pinned, cmp no-op when
# unchanged). Create it now and reuse it for the initial download so there's
# exactly one implementation. The GPG key was imported just above, as it must be
# before the first invocation. The systemd timer wiring comes later.
mkdir -p ~/.local/bin
cat > ~/.local/bin/update-signal-appimage.sh <<'SIGEOF'
#!/usr/bin/env bash
set -euo pipefail

# Signal Desktop's release-signing key fingerprint. The key lives in the default
# gpg keyring (imported by the installer). Verification is BOUND to this
# fingerprint via gpg's VALIDSIG status line below, so extra/unexpected keys in
# the keyring cannot pass verification — only a signature made by this key (or a
# subkey of it) is accepted. Source (official):
#   https://updates.signal.org/static/desktop/appimage.asc
SIGNAL_KEY_FPR="4B16B7232DFAA439AD791002EF9F501F13EED94C"

# Skip cleanly if the network isn't up yet (e.g. the timer fired before
# connectivity) rather than erroring out under set -e.
curl -fsI --max-time 10 https://updates.signal.org >/dev/null 2>&1 \
  || { echo "Signal: network unreachable, skipping."; exit 0; }

dest="$HOME/Applications/Signal.AppImage"
mkdir -p "$HOME/Applications"
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
curl -fL -o "$tmp/Signal.AppImage"     https://updates.signal.org/desktop/signal-desktop.AppImage
curl -fL -o "$tmp/Signal.AppImage.gpg" https://updates.signal.org/desktop/signal-desktop.AppImage.gpg
# Verify the detached signature AND bind it to the pinned key. Plain gpg --verify
# accepts a good signature from ANY key in the default keyring, so we additionally
# require a VALIDSIG status line naming our pinned fingerprint. Capture the status
# output first (|| true) so a failed gpg exit can't be masked by a pipeline under
# set -e; a bad/missing signature yields no VALIDSIG line and we fail closed.
# VALIDSIG format: "VALIDSIG <signing-key-fpr> <date> <ts> ... <primary-key-fpr>",
# so accept the pinned fpr in either the first (signed directly) or last (signed
# by a subkey of the pinned primary) position. grep -a: Signal's signature carries
# a binary NOTATION_DATA line that would otherwise trip grep's binary detection
# and suppress the match on a legitimate signature.
status=$(gpg --status-fd 1 --verify "$tmp/Signal.AppImage.gpg" "$tmp/Signal.AppImage" 2>/dev/null) || true
if ! printf '%s\n' "$status" \
     | grep -aEq "^\[GNUPG:\] VALIDSIG ([0-9A-F]{40} .* )?${SIGNAL_KEY_FPR}( |$)"; then
  echo "Signal: signature not made by pinned key ${SIGNAL_KEY_FPR}; refusing to install." >&2
  exit 1
fi
# Only replace the live AppImage if the file actually changed.
if [ -f "$dest" ] && cmp -s "$tmp/Signal.AppImage" "$dest"; then
  echo "Signal already up to date."
  exit 0
fi
chmod +x "$tmp/Signal.AppImage"
mv -f "$tmp/Signal.AppImage" "$dest"
echo "Signal updated."
SIGEOF
chmod +x ~/.local/bin/update-signal-appimage.sh

# Initial download via the same verified path used weekly.
~/.local/bin/update-signal-appimage.sh

# Pull Signal's own icon out of the AppImage so the launcher isn't a generic
# placeholder. --appimage-extract unpacks without mounting (no FUSE needed) into
# ./squashfs-root. Signal ships .DirIcon as a *symlink*, so we extract the whole
# image and copy with -L to follow it. Best-effort: a failure here must not abort
# the run, and we skip the work entirely once the icon already exists.
mkdir -p ~/.local/share/icons
signal_icon="signal-desktop"   # fallback: themed name (generic if not in a theme)
if [ -f ~/.local/share/icons/signal.png ]; then
  signal_icon="$HOME/.local/share/icons/signal.png"
else
  sig_tmp=$(mktemp -d)
  if ( cd "$sig_tmp" && ~/Applications/Signal.AppImage --appimage-extract >/dev/null 2>&1 ) \
     && cp -L "$sig_tmp/squashfs-root/.DirIcon" ~/.local/share/icons/signal.png 2>/dev/null; then
    signal_icon="$HOME/.local/share/icons/signal.png"
  else
    echo "WARN: could not extract Signal icon from AppImage; launcher will use the themed name."
  fi
  rm -rf "$sig_tmp"
fi

# Desktop launcher for Signal (absolute Icon path → no icon-theme-cache dependency)
mkdir -p ~/.local/share/applications
cat > ~/.local/share/applications/signal.desktop <<EOF
[Desktop Entry]
Name=Signal
Exec=$HOME/Applications/Signal.AppImage %U
Terminal=false
Type=Application
Icon=$signal_icon
Categories=Network;InstantMessaging;Chat;
MimeType=x-scheme-handler/sgnl;x-scheme-handler/signalcaptcha;
StartupWMClass=Signal
EOF
# Register the sgnl:// / signalcaptcha:// scheme handlers (guarded — the tool
# comes from desktop-file-utils, which may not be present on a minimal install).
command -v update-desktop-database &>/dev/null \
  && update-desktop-database ~/.local/share/applications || true

#
# Drop the Fedora flatpak remote (you don't want flatpaks)
#
command -v flatpak &>/dev/null && flatpak remote-delete --force fedora 2>/dev/null || true

#
# YubiKey — lock the session when the key is removed, wake the display when it
# is inserted, and enable the smartcard daemon for PIV / GPG / ykman.
#
# udev rules match VENDOR ONLY (1050 = Yubico): this covers every YubiKey model
# including a backup key of a different model, and means no key has to be
# inserted while this script runs. A YubiKey exposes several USB interfaces, so
# the remove event fires multiple times per unplug; loginctl lock-sessions is
# idempotent, so that's harmless.
#
# The socket path is defined once and used by BOTH the ydotoold unit and the
# udev rule, so they cannot drift apart.
YDOTOOL_SOCKET_PATH="/tmp/.ydotool_socket"

# ydotoold system unit. We always ship our own unit with an explicit
# --socket-path rather than enabling whatever unit the ydotool package may or
# may not provide: Fedora has shipped it as a user unit in some releases (whose
# socket under /run/user/$UID would be unreachable from root udev context), and
# an explicit path is the only way to guarantee it matches the udev rule.
ydotoold_unit="[Unit]
Description=ydotool input daemon (for YubiKey wake-on-insert udev rule)
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/ydotoold --socket-path=${YDOTOOL_SOCKET_PATH} --socket-perm=0600
Restart=on-failure

[Install]
WantedBy=multi-user.target"
if ! diff -q <(printf '%s\n' "$ydotoold_unit") /etc/systemd/system/ydotoold.service &>/dev/null; then
  printf '%s\n' "$ydotoold_unit" | sudo tee /etc/systemd/system/ydotoold.service > /dev/null
  sudo systemctl daemon-reload
fi
sudo systemctl enable --now ydotoold.service

# udev rules: lock on removal, wake display on insertion (key 42 = left shift
# press/release — enough to wake the screen without typing a character).
yubikey_rules="# Lock all sessions when any YubiKey (vendor 1050) is removed
ACTION==\"remove\", ENV{ID_BUS}==\"usb\", ENV{ID_VENDOR_ID}==\"1050\", RUN+=\"/usr/bin/loginctl lock-sessions\"

# Wake the display when any YubiKey is inserted
ACTION==\"add\", ENV{ID_BUS}==\"usb\", ENV{ID_VENDOR_ID}==\"1050\", ENV{YDOTOOL_SOCKET}=\"${YDOTOOL_SOCKET_PATH}\", RUN+=\"/usr/bin/ydotool key 42:1 42:0\""
if ! diff -q <(printf '%s\n' "$yubikey_rules") /etc/udev/rules.d/80-yubikey.rules &>/dev/null; then
  printf '%s\n' "$yubikey_rules" | sudo tee /etc/udev/rules.d/80-yubikey.rules > /dev/null
  sudo udevadm control --reload
fi

# Smartcard daemon (socket-activated — starts on first PIV/GPG/ykman use).
sudo systemctl enable --now pcscd.socket

# NOT automated (interactive, per-key, with the key inserted):
#  - FIDO2 PAM enrollment:  mkdir -p ~/.config/Yubico && pamu2fcfg >> ~/.config/Yubico/u2f_keys
#    (run once per key, INCLUDING the backup key), then add pam_u2f to the
#    desired PAM stack, e.g. /etc/pam.d/sudo. CAUTION: a broken PAM edit can
#    lock you out — 'sufficient' vs 'required' placement matters; keep a root
#    shell open while testing.
#  - PIN / touch policy:    ykman fido access change-pin, ykman piv access, etc.
#  - SSH resident keys:     ssh-keygen -t ed25519-sk -O resident
#  - GPG smartcard check:   gpg --card-status   (needs pcscd, enabled above)

#
# PIV smartcard (USDA CAC-style login certs) in Chrome / Edge / Firefox
#
# Hardware: a USB CCID reader (e.g. Alcor Micro AU9540) + the USDA PIV card.
# opensc (dnf #3) is the PKCS#11 module that reads PIV cards, AND it ships
# /usr/share/p11-kit/modules/opensc.module. That .module file is the whole
# trick: p11-kit auto-registers OpenSC system wide, and NSS (Chrome/Edge/
# Firefox) auto-loads it via p11-kit-proxy. So the card's certs appear in every
# browser with NO per-user setup — no modutil, no poking ~/.pki/nssdb.
# (Manually `modutil -add`ing opensc-pkcs11.so here would be wrong: it
# double-registers and NSS rejects it.)
#
# pcscd.socket is already enabled in the YubiKey section above; the same daemon
# serves the CCID reader. Verify (optional): `opensc-tool -l` should list the
# reader with "Card: Yes", and `p11-kit list-modules` should show the PIV_II
# token under "module: opensc".
#
# Cert-chain trust — REQUIRED, not optional. A browser will only *offer* a client
# cert if it can build a chain from that cert to a CA in its trust store. A fresh
# ~/.pki/nssdb is EMPTY, so Chrome silently offers nothing and the site returns
# "Client SSL Certificate Required" with no cert prompt. We must import the issuing
# chain. USDA PIV leaf certs are issued by "Entrust Managed Services SSP CA", which
# chains to the self-signed "Entrust Managed Services Root CA" (and, via key
# rollover/cross-cert, to the Federal Common Policy CA G2 root).
#
# Rather than hard-code certs (key generations rotate), the helper below reads the
# PIV Authentication cert off whatever card is inserted, follows its AIA caIssuers
# pointers up the chain, trusts every self-signed root it lands on, and imports the
# rest as chain-building intermediates. It also pins in the FCPCA G2 root from the
# official Federal PKI repo. Idempotent; safe to re-run.
mkdir -p ~/.local/bin
cat > ~/.local/bin/import-piv-cas.sh <<'PIVEOF'
#!/usr/bin/env bash
# Import the USDA/Federal PIV CA chain into the per-user NSS db so Chrome/Edge/
# Firefox will offer the card's client cert. Run once with the card inserted.
# NOT set -e: chain gathering is best-effort (failed AIA fetches / non-cert blobs
# are expected and handled inline; a stray nonzero must not abort the whole run).
set -uo pipefail
DB="sql:$HOME/.pki/nssdb"
FCPCA_URL="http://repo.fpki.gov/fcpca/fcpcag2.crt"

# Self-reliant: ensure every CLI we use exists; install the providing package if not.
declare -A NEED=( [certutil]=nss-tools [pkcs11-tool]=opensc [opensc-tool]=opensc [openssl]=openssl [curl]=curl )
miss=()
for t in "${!NEED[@]}"; do command -v "$t" >/dev/null 2>&1 || miss+=("${NEED[$t]}"); done
if [ "${#miss[@]}" -gt 0 ]; then
  # de-dup package list
  mapfile -t miss < <(printf '%s\n' "${miss[@]}" | sort -u)
  echo "Installing missing dependencies: ${miss[*]}"
  sudo dnf -y install "${miss[@]}" || { echo "Could not install: ${miss[*]} — install them and re-run."; exit 1; }
fi
# pcscd must be running to reach the reader; start it if a prior step didn't.
systemctl is-active --quiet pcscd 2>/dev/null || sudo systemctl enable --now pcscd.socket 2>/dev/null || true

# Create the NSS db if no browser has made one yet (empty password, like browsers do).
[ -f "$HOME/.pki/nssdb/cert9.db" ] || { mkdir -p "$HOME/.pki/nssdb"; certutil -d "$DB" -N --empty-password; }

work=$(mktemp -d); trap 'rm -rf "$work"' EXIT; cd "$work" || exit 1

# PIV Authentication cert is always object id 0x01 on a PIV card.
if ! pkcs11-tool --read-object --type cert --id 1 >leaf.der 2>/dev/null; then
  echo "No PIV card / reader found — insert the card and retry."; exit 1
fi
openssl x509 -inform DER -in leaf.der -out leaf.pem

seen="$work/seen.txt"; : >"$seen"
import_cert() {  # $1=pemfile
  local f="$1" subj iss fp nick short
  # Skip anything that isn't a parseable X.509 cert (e.g. pkcs7 header text).
  openssl x509 -in "$f" -noout >/dev/null 2>&1 || return 0
  # Strip openssl's "subject="/"issuer=" prefixes so a self-signed cert compares equal.
  subj=$(openssl x509 -in "$f" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$f" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  fp=$(openssl x509 -in "$f" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
  grep -qF "$fp" "$seen" && return 0; echo "$fp" >>"$seen"
  short=$(echo "$subj" | grep -oiE '(CN|OU)=[^,]+' | head -1 | cut -d= -f2-)
  nick="${short:-CA} ${fp:0:8}"
  if [ "$subj" = "$iss" ]; then              # self-signed root -> trust anchor
    certutil -d "$DB" -A -n "$nick" -t "CT,C,C" -i "$f" 2>/dev/null && echo "  trusted root : $nick"
  else                                        # intermediate -> chain material only
    certutil -d "$DB" -A -n "$nick" -t ",,"    -i "$f" 2>/dev/null && echo "  intermediate : $nick"
  fi
}

# Key-identifier helpers — used to follow ONLY the true parent at each hop.
ski() { openssl x509 -in "$1" -noout -text 2>/dev/null | grep -A1 "Subject Key Identifier"   | tail -1 | tr -d ' '; }
aki() { openssl x509 -in "$1" -noout -text 2>/dev/null | grep -A1 "Authority Key Identifier" | tail -1 | tr -d ' ' | sed 's/keyid://'; }

# Walk the issuer chain UPWARD. At each cert, fetch its caIssuers AIA and pick the
# ONE real parent — the cert whose Subject Key Identifier equals our Authority Key
# Identifier (falling back to subject-DN == issuer-DN only when no AKI is present).
# Matching by key id is essential: USDA's root went through a key rollover, so
# several certs share the "Entrust Managed Services Root CA" name but only one is
# the actual signer. Following every name/cross-cert instead would wander the
# entire Federal Bridge mesh (DoD, CertiPath, Boeing, ...) and never finish.
# Recursion stops at the self-signed root, which import_cert marks as a trust anchor.
chase() {  # $1=pemfile $2=depth
  local f="$1" d="${2:-0}" subj iss want u tmp certs c csub ciss best best_root chosen
  [ "$d" -gt 8 ] && return
  subj=$(openssl x509 -in "$f" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$f" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  [ "$subj" = "$iss" ] && return          # self-signed root: nothing above it
  want=$(aki "$f")                         # the issuer key id we must match
  for u in $(openssl x509 -in "$f" -noout -text 2>/dev/null \
             | grep -oE 'CA Issuers - URI:http://[^ ]+' | sed 's/CA Issuers - URI://'); do
    tmp=$(mktemp); curl -fsS --max-time 20 -o "$tmp" "$u" || { rm -f "$tmp"; continue; }
    certs=$(mktemp)
    openssl pkcs7 -inform DER -in "$tmp" -print_certs 2>/dev/null >"$certs" \
      || openssl x509 -inform DER -in "$tmp" 2>/dev/null >"$certs" || { rm -f "$tmp" "$certs"; continue; }
    # Split into per-cert files; n>0 guard drops pkcs7's pre-cert header lines.
    ( cd "$work" && awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("seg"n".pem")}' "$certs" )
    # Among the returned certs, find the true parent (Subject Key Id == our AKI,
    # or subject DN == our issuer DN when no AKI). A CA key rollover yields several
    # certs for the same key; PREFER the self-signed copy so the walk terminates at
    # the root instead of climbing cross-certs into the Federal Bridge mesh.
    best=""; best_root=""
    for c in "$work"/seg*.pem; do
      [ -s "$c" ] || continue
      openssl x509 -in "$c" -noout >/dev/null 2>&1 || { rm -f "$c"; continue; }
      csub=$(openssl x509 -in "$c" -noout -subject -nameopt RFC2253 2>/dev/null); csub=${csub#subject=}
      ciss=$(openssl x509 -in "$c" -noout -issuer  -nameopt RFC2253 2>/dev/null); ciss=${ciss#issuer=}
      if { [ -n "$want" ] && [ "$(ski "$c")" = "$want" ]; } \
         || { [ -z "$want" ] && [ "$csub" = "$iss" ]; }; then
        if [ "$csub" = "$ciss" ]; then cp "$c" "$work/parent_root.pem"; best_root="$work/parent_root.pem"
        else                           cp "$c" "$work/parent.pem";      best="$work/parent.pem"; fi
      fi
      rm -f "$c"
    done
    rm -f "$tmp" "$certs"
    chosen="${best_root:-$best}"
    if [ -n "$chosen" ]; then
      import_cert "$chosen"; chase "$chosen" $((d+1)); rm -f "$work/parent_root.pem" "$work/parent.pem"
      return                               # parent found — skip remaining AIA URLs
    fi
  done
}

echo "Importing PIV CA chain into $DB ..."
chase leaf.pem 0

# Always pin the Federal Common Policy CA G2 root straight from the FPKI repo.
if curl -fsS --max-time 25 -o fcpca.crt "$FCPCA_URL"; then
  openssl x509 -inform DER -in fcpca.crt -out fcpca.pem && import_cert fcpca.pem
fi

echo
echo "nssdb CA list:"; certutil -d "$DB" -L
echo
if certutil -d "$DB" -V -u C -n "PIV_II:Certificate for PIV Authentication" </dev/null 2>/dev/null; then
  echo "OK: PIV Authentication cert validates for TLS client auth."
  echo "Restart your browser, open the USDA site, pick 'PIV Authentication', enter PIN."
else
  echo "Imported, but couldn't auto-verify the token cert (token label may differ)."
fi
PIVEOF
chmod +x ~/.local/bin/import-piv-cas.sh

#
# Federal/USDA PKI — card-free variant. The chain-chaser above needs the card
# (it walks UP from the leaf). This helper needs nothing: it trusts the FCPCA G2
# root and walks DOWN the Federal PKI via each CA cert's SIA (Subject Information
# Access) repository bundle — descending ONLY into the Entrust branch that issues
# USDA PIV certs, so it doesn't crawl the entire FPKI/Bridge mesh. Either helper
# alone is sufficient for USDA; running both is harmless (same nssdb, dedup'd).
cat > ~/.local/bin/import-federal-cas.sh <<'FEDEOF'
#!/usr/bin/env bash
# Card-free import of the Federal/USDA PIV trust chain into the per-user NSS db.
# Trusts FCPCA G2, then imports the Entrust SSP branch (cross-certs + issuing
# CAs) as chain material by following SIA repository bundles downward.
# Idempotent; safe to re-run. NOT set -e: bundle fetching is best-effort.
set -uo pipefail
DB="sql:$HOME/.pki/nssdb"
FCPCA_URL="http://repo.fpki.gov/fcpca/fcpcag2.crt"
FCPCA_SIA_FALLBACK="http://repo.fpki.gov/fcpca/caCertsIssuedByfcpcag2.p7c"
# Direct seed for the USDA branch, independent of SIA discovery through the
# cross-cert: the Entrust Managed Services Root CA's own SIA bundle, which
# contains the "Entrust Managed Services SSP CA" that issues USDA PIV certs
# (URL confirmed by card recon + GSA FPKI notifications). Belt and suspenders —
# processed even if the walk from FCPCA already found it (dedup'd by fingerprint).
EXTRA_SIA_SEEDS="http://rootweb.managed.entrust.com/SIA/CertsIssuedByEMSRootCA.p7c"
BRANCH_FILTER="entrust"   # descend only into CAs matching this (USDA's SSP branch)

for t in certutil openssl curl; do
  command -v "$t" >/dev/null 2>&1 || { echo "Missing $t — install nss-tools/openssl/curl and re-run." >&2; exit 1; }
done
[ -f "$HOME/.pki/nssdb/cert9.db" ] || { mkdir -p "$HOME/.pki/nssdb"; certutil -d "$DB" -N --empty-password; }
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT; cd "$work" || exit 1

seen="$work/seen.txt"; : >"$seen"
import_cert() {  # $1=pemfile
  local f="$1" subj iss fp nick short
  openssl x509 -in "$f" -noout >/dev/null 2>&1 || return 0
  subj=$(openssl x509 -in "$f" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$f" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  fp=$(openssl x509 -in "$f" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
  grep -qF "$fp" "$seen" && return 0; echo "$fp" >>"$seen"
  short=$(echo "$subj" | grep -oiE '(CN|OU)=[^,]+' | head -1 | cut -d= -f2-)
  nick="${short:-CA} ${fp:0:8}"
  if [ "$subj" = "$iss" ]; then              # self-signed root -> trust anchor
    certutil -d "$DB" -A -n "$nick" -t "CT,C,C" -i "$f" 2>/dev/null && echo "  trusted root : $nick"
  else                                        # intermediate -> chain material only
    certutil -d "$DB" -A -n "$nick" -t ",,"    -i "$f" 2>/dev/null && echo "  intermediate : $nick"
  fi
}

sia_urls() {  # $1=pemfile — print the CA Repository URIs from the SIA extension
  openssl x509 -in "$1" -noout -text 2>/dev/null \
    | grep -oE 'CA Repository - URI:https?://[^ ]+' | sed 's/CA Repository - URI://'
}

# Fetch one SIA/AIA-style p7c bundle, import every cert in it, and recurse into
# the SIA of certs matching BRANCH_FILTER. Depth-capped; fingerprints dedup'd.
process_bundle() {  # $1=url $2=depth
  local url="$1" d="${2:-0}" tmp certs segdir c u2
  [ "$d" -gt 3 ] && return
  tmp=$(mktemp); curl -fsS --max-time 25 -o "$tmp" "$url" || { rm -f "$tmp"; return; }
  certs=$(mktemp)
  openssl pkcs7 -inform DER -in "$tmp" -print_certs 2>/dev/null >"$certs" \
    || openssl pkcs7 -in "$tmp" -print_certs 2>/dev/null >"$certs" \
    || openssl x509 -inform DER -in "$tmp" 2>/dev/null >"$certs" \
    || { rm -f "$tmp" "$certs"; return; }
  segdir=$(mktemp -d -p "$work")
  ( cd "$segdir" && awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("seg"n".pem")}' "$certs" )
  for c in "$segdir"/seg*.pem; do
    [ -s "$c" ] || continue
    openssl x509 -in "$c" -noout >/dev/null 2>&1 || continue
    import_cert "$c"
    if openssl x509 -in "$c" -noout -subject 2>/dev/null | grep -qi "$BRANCH_FILTER"; then
      for u2 in $(sia_urls "$c"); do process_bundle "$u2" $((d+1)); done
    fi
  done
  rm -rf "$tmp" "$certs" "$segdir"
}

echo "Importing Federal/USDA PIV trust chain (card-free) into $DB ..."
if ! curl -fsS --max-time 25 -o fcpca.crt "$FCPCA_URL"; then
  echo "Could not fetch the FCPCA G2 root from $FCPCA_URL — check network and re-run." >&2
  exit 1
fi
openssl x509 -inform DER -in fcpca.crt -out fcpca.pem 2>/dev/null \
  || openssl x509 -in fcpca.crt -out fcpca.pem 2>/dev/null \
  || { echo "Fetched FCPCA file is not a certificate." >&2; exit 1; }
import_cert fcpca.pem

# Walk down from the root's own SIA; fall back to the published bundle URL if
# the SIA extension can't be parsed for any reason.
urls=$(sia_urls fcpca.pem)
[ -n "$urls" ] || urls="$FCPCA_SIA_FALLBACK"
for u in $urls; do process_bundle "$u" 0; done
# Direct branch seeds (see EXTRA_SIA_SEEDS above) — idempotent with the walk.
for u in $EXTRA_SIA_SEEDS; do process_bundle "$u" 1; done

echo "Federal PKI import complete ($(wc -l < "$seen") certs processed into $DB)."
FEDEOF
chmod +x ~/.local/bin/import-federal-cas.sh

#
# DoD PKI — import the complete official CA bundle (all roots + intermediates)
# into the per-user NSS db. No card required, so this runs unconditionally.
#
# Trust scope is DELIBERATELY the per-user nssdb, not /etc/pki/ca-trust anchors:
# system-wide anchors would make every TLS client on the box trust DoD CAs for
# all connections. The user nssdb is exactly what Chrome/Edge/Firefox consult
# for client-cert chain building and for DoD-issued server certs — which is the
# actual need.
#
# The zip URL is DISA's stable, unversioned bundle location; the p7b naming
# INSIDE the zip has changed across releases, so the helper globs for it.
cat > ~/.local/bin/import-dod-cas.sh <<'DODEOF'
#!/usr/bin/env bash
# Import the DoD PKI CA bundle (roots trusted, intermediates as chain material)
# into the per-user NSS db. Idempotent; safe to re-run.
set -uo pipefail
DB="sql:$HOME/.pki/nssdb"
DOD_ZIP_URL="https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/unclass-certificates_pkcs7_DoD.zip"

for t in certutil openssl curl unzip; do
  command -v "$t" >/dev/null 2>&1 || { echo "Missing $t — install nss-tools/openssl/curl/unzip and re-run." >&2; exit 1; }
done

# Create the NSS db if no browser has made one yet (empty password, like browsers do).
[ -f "$HOME/.pki/nssdb/cert9.db" ] || { mkdir -p "$HOME/.pki/nssdb"; certutil -d "$DB" -N --empty-password; }

work=$(mktemp -d); trap 'rm -rf "$work"' EXIT; cd "$work" || exit 1

echo "Fetching DoD PKI CA bundle ..."
curl -fsSL --max-time 60 -o dod.zip "$DOD_ZIP_URL" || { echo "DoD bundle download failed." >&2; exit 1; }
unzip -qj dod.zip -d bundle || { echo "DoD bundle unzip failed." >&2; exit 1; }

# Find the main DoD p7b case-insensitively; prefer the PEM-encoded variant.
shopt -s nullglob nocaseglob
p7b=""
for f in bundle/*dod*pem*.p7b; do p7b="$f"; break; done
if [ -z "$p7b" ]; then for f in bundle/*dod*.p7b; do p7b="$f"; break; done; fi
shopt -u nullglob nocaseglob
[ -n "$p7b" ] || { echo "No DoD .p7b found in bundle (naming changed?) — inspect the zip manually." >&2; exit 1; }
echo "Using bundle file: $(basename "$p7b")"

# Explode the PKCS#7 into individual PEM certs (try PEM parse, then DER).
openssl pkcs7 -print_certs -in "$p7b" >certs.pem 2>/dev/null \
  || openssl pkcs7 -print_certs -inform DER -in "$p7b" >certs.pem 2>/dev/null \
  || { echo "Could not parse $p7b as PKCS#7." >&2; exit 1; }
awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("seg" n ".pem")}' certs.pem

roots=0; inters=0
for c in seg*.pem; do
  [ -s "$c" ] || continue
  openssl x509 -in "$c" -noout >/dev/null 2>&1 || continue
  subj=$(openssl x509 -in "$c" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$c" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  fp=$(openssl x509 -in "$c" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
  short=$(echo "$subj" | grep -oiE 'CN=[^,]+' | head -1 | cut -d= -f2-)
  nick="${short:-DoD CA} ${fp:0:8}"
  if [ "$subj" = "$iss" ]; then              # self-signed root -> trust anchor
    certutil -d "$DB" -A -n "$nick" -t "CT,C,C" -i "$c" 2>/dev/null && { echo "  trusted root : $nick"; roots=$((roots+1)); }
  else                                        # intermediate -> chain material only
    certutil -d "$DB" -A -n "$nick" -t ",,"    -i "$c" 2>/dev/null && { echo "  intermediate : $nick"; inters=$((inters+1)); }
  fi
done
echo "DoD PKI import complete: $roots roots trusted, $inters intermediates added to $DB."
DODEOF
chmod +x ~/.local/bin/import-dod-cas.sh

#
# Fleet verification + card diagnostics — generated onto PATH so every host set
# up by this one file can prove its own trust state.
#
#   verify-pki-trust.sh [leaf.pem]  card-free PASS/FAIL of USDA + DoD trust
#                                   (exit 0/1 — usable over ssh across hosts);
#                                   if a PIV card is inserted it also validates
#                                   the real leaf read live from the card.
#   piv-card-recon.sh               read-only deep diagnostic with the card in:
#                                   stack health, cert inventory, chain walk.
#
cat > ~/.local/bin/verify-pki-trust.sh <<'VERIFYEOF'
#!/usr/bin/env bash
#
# verify-pki-trust.sh [path/to/piv-auth-leaf.pem]
#
# Card-free verification that a machine set up by fedora_stuff.sh can actually
# validate USDA PIV and DoD chains. Run on ANY host — no PIV card, no reader
# needed. Exit code 0 = all checks pass, nonzero = something failed, so it can
# be driven over SSH across a fleet:
#
#   for h in host1 host2; do ssh "$h" 'bash -s' < verify-pki-trust.sh \
#       && echo "$h OK" || echo "$h FAILED"; done
#
# GOLD-STANDARD MODE: pass your exported PIV Authentication cert (public — safe
# to copy between your machines) as $1 and the script validates that exact leaf
# for TLS client auth against this host's trust store — byte-for-byte the same
# evaluation a browser performs when deciding whether to offer your cert.
# Export it once on the host that has the card:
#   pkcs11-tool --read-object --type cert --id 1 2>/dev/null \
#     | openssl x509 -inform DER -out ~/piv-auth-leaf.pem
#
# Checks performed:
#   1. nssdb exists
#   2. FCPCA G2 present and TRUSTED
#   3. Entrust Managed Services SSP CA present (USDA's issuing CA)
#   4. LIVE chain validation: fetch the real SSP CA cert from Entrust's AIA and
#      validate it as an SSL CA against this trust store
#   5. DoD Root CAs present and TRUSTED
#   6. (optional, with $1) your actual leaf validates for TLS client auth
#
set -uo pipefail

DB_DIR="$HOME/.pki/nssdb"
DB="sql:$DB_DIR"
SSP_AIA_URL="http://sspweb.managed.entrust.com/AIA/CertsIssuedToEMSSSPCA.p7c"
LEAF="${1:-}"

pass=0; fail=0
ok()  { printf '  [PASS] %s\n' "$*"; pass=$((pass+1)); }
bad() { printf '  [FAIL] %s\n' "$*"; fail=$((fail+1)); }
info(){ printf '  [ -- ] %s\n' "$*"; }
hr()  { printf -- '---------------------------------------------------------------\n'; }

for t in certutil openssl curl; do
  command -v "$t" >/dev/null 2>&1 || { echo "Missing $t — run fedora_stuff.sh first (or dnf install nss-tools openssl curl)."; exit 2; }
done

work=$(mktemp -d); trap 'rm -rf "$work"' EXIT

# Validate a cert file against the nssdb by temporary import (nick is unique and
# removed afterwards, pass or fail). certutil -V is the NSS chain engine itself.
#   $1 = pemfile, $2 = usage flag for certutil -V (C = SSL client, L = SSL CA)
validate_file() {
  local f="$1" usage="$2" nick rc=1
  nick="__verify_tmp_$$_${RANDOM}"
  if certutil -d "$DB" -A -n "$nick" -t ",," -i "$f" 2>/dev/null; then
    if certutil -d "$DB" -V -u "$usage" -n "$nick" </dev/null >/dev/null 2>&1; then rc=0; fi
    certutil -d "$DB" -D -n "$nick" 2>/dev/null
  fi
  return "$rc"
}

hr; echo "PKI trust verification — $(hostname) — $DB"

# 1. nssdb exists
if [ -f "$DB_DIR/cert9.db" ]; then
  ok "nssdb exists"
else
  bad "no nssdb at $DB_DIR — fedora_stuff.sh imports have not run for this user"
  hr; echo "RESULT: FAILED ($fail failure(s))"; exit 1
fi

nsslist=$(certutil -d "$DB" -L 2>/dev/null | tail -n +5)

# 2. FCPCA G2 present and trusted (trust column contains C or T)
fcp_line=$(echo "$nsslist" | grep -i 'federal common policy' | head -1 || true)
if [ -n "$fcp_line" ] && echo "$fcp_line" | awk '{print $NF}' | grep -qE '[CT]'; then
  ok "Federal Common Policy CA G2 present and trusted"
elif [ -n "$fcp_line" ]; then
  bad "FCPCA G2 present but NOT trusted (trust: $(echo "$fcp_line" | awk '{print $NF}')) — re-run import-federal-cas.sh"
else
  bad "FCPCA G2 not in nssdb — run import-federal-cas.sh"
fi

# 3. USDA's issuing CA present as chain material
if echo "$nsslist" | grep -qi 'entrust managed services ssp'; then
  ok "Entrust Managed Services SSP CA (USDA issuer) present"
else
  bad "Entrust Managed Services SSP CA not in nssdb — run import-federal-cas.sh"
fi

# 4. LIVE chain proof: fetch the real SSP CA cert from Entrust's AIA repository
#    and ask NSS to validate it as an SSL CA against this machine's trust store.
#    This exercises the actual chain (SSP -> EMS Root [-> FCPCA]) end to end.
if curl -fsS --max-time 25 -o "$work/ssp.p7c" "$SSP_AIA_URL"; then
  if openssl pkcs7 -inform DER -in "$work/ssp.p7c" -print_certs 2>/dev/null >"$work/ssp_all.pem" \
     || openssl pkcs7 -in "$work/ssp.p7c" -print_certs 2>/dev/null >"$work/ssp_all.pem"; then
    awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("'"$work"'/ssp" n ".pem")}' "$work/ssp_all.pem"
    live_ok=0
    for c in "$work"/ssp[0-9]*.pem; do
      [ -s "$c" ] || continue
      openssl x509 -in "$c" -noout 2>/dev/null || continue
      if validate_file "$c" L; then live_ok=1; break; fi
    done
    if [ "$live_ok" -eq 1 ]; then
      ok "LIVE: real Entrust SSP CA cert validates as SSL CA against this trust store"
    else
      bad "LIVE: fetched SSP CA cert does NOT validate — chain to a trust anchor is broken here"
    fi
  else
    info "LIVE check skipped: could not parse the fetched AIA bundle"
  fi
else
  info "LIVE check skipped: could not reach $SSP_AIA_URL (offline?) — static checks above still stand"
fi

# 5. DoD roots present and trusted
dod_total=$(echo "$nsslist" | grep -ci 'dod root ca' || true)
dod_trusted=$(echo "$nsslist" | grep -i 'dod root ca' | awk '{print $NF}' | grep -cE '[CT]' || true)
if [ "${dod_trusted:-0}" -ge 1 ]; then
  ok "DoD Root CAs: $dod_trusted trusted (of $dod_total present)"
else
  bad "No trusted DoD Root CAs in nssdb — run import-dod-cas.sh"
fi

# 6. Gold standard: validate the actual PIV Authentication leaf. Source
#    priority: $1 argument, else read live from an inserted PIV card, else skip.
if [ -z "$LEAF" ] && command -v pkcs11-tool >/dev/null 2>&1 \
   && opensc-tool -l 2>/dev/null | grep -q 'Yes'; then
  if pkcs11-tool --read-object --type cert --id 1 2>/dev/null \
       | openssl x509 -inform DER -out "$work/card-leaf.pem" 2>/dev/null; then
    LEAF="$work/card-leaf.pem"
    info "Gold-standard leaf read live from the inserted PIV card."
  fi
fi
if [ -n "$LEAF" ]; then
  if [ ! -f "$LEAF" ]; then
    bad "leaf file not found: $LEAF"
  elif ! openssl x509 -in "$LEAF" -noout 2>/dev/null; then
    bad "leaf file is not a PEM certificate: $LEAF (export with the pkcs11-tool one-liner in the header)"
  elif validate_file "$LEAF" C; then
    ok "GOLD: your PIV Authentication leaf validates for TLS CLIENT AUTH on this host"
  else
    bad "GOLD: your leaf does NOT validate here — a chain link is missing on this host"
  fi
else
  info "No leaf supplied and no PIV card inserted — gold-standard check skipped."
  info "(Optional: export the public leaf on the card host with"
  info "  pkcs11-tool --read-object --type cert --id 1 | openssl x509 -inform DER -out ~/piv-auth-leaf.pem"
  info " and pass its path as \$1 on other hosts.)"
fi

hr
if [ "$fail" -eq 0 ]; then
  echo "RESULT: OK — $pass check(s) passed. This host will offer PIV certs and trust DoD chains."
  exit 0
else
  echo "RESULT: FAILED — $fail failure(s), $pass pass(es). See FAIL lines above."
  exit 1
fi
VERIFYEOF
chmod +x ~/.local/bin/verify-pki-trust.sh

cat > ~/.local/bin/piv-card-recon.sh <<'RECONEOF'
#!/usr/bin/env bash
#
# piv-card-recon.sh — READ-ONLY reconnaissance of a PIV card and the local
# trust state. Changes NOTHING: no imports, no config writes. It answers:
#
#   1. Is the smartcard stack healthy? (pcscd, reader, card, p11-kit/OpenSC)
#   2. What certificates are on the card? (all slots: subject/issuer/validity)
#   3. What CA chain does the PIV Authentication cert need, hop by hop?
#      (follows AIA caIssuers with SKI/AKI parent matching — same logic as
#       import-piv-cas.sh, but reporting instead of importing)
#   4. Which of those CAs are already in ~/.pki/nssdb, and with what trust?
#   5. What should BRANCH_FILTER in import-federal-cas.sh be for THIS card?
#
# Run with the card inserted:  ./piv-card-recon.sh
# Paste the full output back for analysis.
#
set -uo pipefail

DB="sql:$HOME/.pki/nssdb"
ok()   { printf '  [ OK ] %s\n' "$*"; }
bad()  { printf '  [FAIL] %s\n' "$*"; }
info() { printf '  [ -- ] %s\n' "$*"; }
hr()   { printf -- '---------------------------------------------------------------\n'; }

# ── 0. Dependencies (report, don't install) ─────────────────────────────────
hr; echo "0. Tooling"
missing=0
for t in pkcs11-tool opensc-tool openssl curl certutil p11-kit; do
  if command -v "$t" >/dev/null 2>&1; then ok "$t $(command -v "$t")"
  else bad "$t missing"; missing=1; fi
done
[ "$missing" -eq 1 ] && { echo; echo "Install missing tools (dnf: opensc nss-tools openssl p11-kit) and re-run."; exit 1; }

# ── 1. Smartcard stack health ───────────────────────────────────────────────
hr; echo "1. Smartcard stack"
if systemctl is-active --quiet pcscd 2>/dev/null || systemctl is-active --quiet pcscd.socket 2>/dev/null; then
  ok "pcscd is active (service or socket)"
else
  info "pcscd not currently active (socket activation may start it on demand)"
fi

readers=$(opensc-tool -l 2>/dev/null || true)
if [ -z "$readers" ] || echo "$readers" | grep -qi 'No smart card readers'; then
  bad "No smartcard reader detected. Plug in the reader and re-run."
  exit 1
fi
# shellcheck disable=SC2001  # multi-line indent; sed is the clear tool here
echo "$readers" | sed 's/^/       /'
if echo "$readers" | grep -q 'Yes'; then
  ok "Card present in reader"
else
  bad "Reader present but NO card detected. Insert the PIV card and re-run."
  exit 1
fi
card_name=$(opensc-tool -n 2>/dev/null || echo "unknown")
info "Card recognized as: $card_name"

if p11-kit list-modules 2>/dev/null | grep -qi 'opensc'; then
  ok "OpenSC PKCS#11 module registered with p11-kit (browsers will see the card)"
else
  bad "OpenSC module NOT visible to p11-kit — browsers won't see the card. Check the opensc package."
fi

# ── 2. Certificate inventory on the card ────────────────────────────────────
hr; echo "2. Certificates on the card"
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT

# Enumerate certificate object IDs from the token.
mapfile -t cert_ids < <(pkcs11-tool --list-objects --type cert 2>/dev/null \
  | grep -oE 'ID:[[:space:]]*[0-9a-fA-F]+' | awk '{print $2}' | sort -u)
if [ "${#cert_ids[@]}" -eq 0 ]; then
  bad "pkcs11-tool sees no certificate objects on the card."
  exit 1
fi

leaf=""   # will hold the PIV Authentication cert (id 01) for the chain walk
for id in "${cert_ids[@]}"; do
  der="$work/card_$id.der"; pem="$work/card_$id.pem"
  pkcs11-tool --read-object --type cert --id "$id" >"$der" 2>/dev/null || continue
  openssl x509 -inform DER -in "$der" -out "$pem" 2>/dev/null || continue
  subj=$(openssl x509 -in "$pem" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$pem" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  na=$(openssl x509 -in "$pem" -noout -enddate 2>/dev/null | cut -d= -f2)
  eku=$(openssl x509 -in "$pem" -noout -ext extendedKeyUsage 2>/dev/null | tail -n +2 | tr -d ' ' | tr '\n' ' ')
  echo "  slot id $id:"
  echo "     subject : $subj"
  echo "     issuer  : $iss"
  echo "     expires : $na"
  [ -n "$eku" ] && echo "     EKU     : $eku"
  if openssl x509 -in "$pem" -checkend 0 >/dev/null 2>&1; then :; else bad "  slot $id cert is EXPIRED"; fi
  case "$id" in 01|1) leaf="$pem" ;; esac
done
if [ -z "$leaf" ]; then
  bad "No PIV Authentication cert (object id 01) found — chain walk skipped."
  exit 1
fi

# The issuer O= / OU= of the leaf is what import-federal-cas.sh must branch into.
leaf_iss=$(openssl x509 -in "$leaf" -noout -issuer -nameopt RFC2253 2>/dev/null); leaf_iss=${leaf_iss#issuer=}
suggest_org=$(echo "$leaf_iss" | grep -oE 'O=[^,]+' | head -1 | cut -d= -f2-)

# ── 3. nssdb fingerprint inventory (so each chain hop can be checked) ───────
hr; echo "3. Local trust store ($DB)"
declare -A NSS_TRUST=()
if [ -f "$HOME/.pki/nssdb/cert9.db" ]; then
  # certutil -L lines: <nickname ...> <trust>. Nickname may contain spaces, so
  # split on the LAST whitespace-separated field.
  while IFS= read -r line; do
    line="${line%"${line##*[![:space:]]}"}"   # rtrim: certutil pads the trust column
    trust=${line##* }; nick=${line%"$trust"}
    nick="${nick%"${nick##*[![:space:]]}"}"   # trim trailing whitespace (no extglob needed)
    [ -n "$nick" ] || continue
    pemtmp="$work/nss_one.pem"
    certutil -d "$DB" -L -n "$nick" -a >"$pemtmp" 2>/dev/null || continue
    # A nickname can hold multiple certs; fingerprint each.
    awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("'"$work"'/nsseg" n ".pem")}' "$pemtmp"
    for f in "$work"/nsseg*.pem; do
      [ -s "$f" ] || continue
      fp=$(openssl x509 -in "$f" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
      [ -n "$fp" ] && NSS_TRUST["$fp"]="$trust"
      rm -f "$f"
    done
  done < <(certutil -d "$DB" -L 2>/dev/null | tail -n +5)
  echo "  nssdb exists with ${#NSS_TRUST[@]} certificate(s) loaded."
else
  info "No ~/.pki/nssdb yet (no browser has created one and no import has run)."
fi

nss_status() {  # $1=pemfile -> prints trust state of this exact cert in nssdb
  local fp t
  fp=$(openssl x509 -in "$1" -noout -fingerprint -sha256 2>/dev/null | cut -d= -f2)
  t="${NSS_TRUST[$fp]:-}"
  if [ -z "$t" ]; then echo "MISSING from nssdb"
  elif [[ "$t" == *C* ]] || [[ "$t" == *T* ]]; then echo "present, TRUSTED ($t)"
  else echo "present, chain-only ($t)"; fi
}

# ── 4. Dry-run chain walk (AIA upward, SKI/AKI parent matching) ─────────────
hr; echo "4. Chain the PIV Authentication cert requires (leaf -> root)"
ski() { openssl x509 -in "$1" -noout -text 2>/dev/null | grep -A1 "Subject Key Identifier"   | tail -1 | tr -d ' '; }
aki() { openssl x509 -in "$1" -noout -text 2>/dev/null | grep -A1 "Authority Key Identifier" | tail -1 | tr -d ' ' | sed 's/keyid://'; }

hop=0
cur="$leaf"
subj=$(openssl x509 -in "$cur" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
echo "  [$hop] LEAF: $subj"
echo "        (leaf lives on the card; it is never imported anywhere)"

while :; do
  hop=$((hop+1)); [ "$hop" -gt 8 ] && { bad "chain longer than 8 hops? stopping."; break; }
  subj=$(openssl x509 -in "$cur" -noout -subject -nameopt RFC2253 2>/dev/null); subj=${subj#subject=}
  iss=$(openssl x509 -in "$cur" -noout -issuer  -nameopt RFC2253 2>/dev/null); iss=${iss#issuer=}
  [ "$subj" = "$iss" ] && break   # reached the self-signed root
  want=$(aki "$cur")
  mapfile -t aia_urls < <(openssl x509 -in "$cur" -noout -text 2>/dev/null \
      | grep -oE 'CA Issuers - URI:https?://[^ ]+' | sed 's/CA Issuers - URI://')
  if [ "${#aia_urls[@]}" -eq 0 ]; then
    bad "  [$hop] cert has NO AIA caIssuers URL — chain cannot be auto-discovered above: $subj"
    break
  fi
  parent=""
  for u in "${aia_urls[@]}"; do
    tmp="$work/aia.bin"
    curl -fsS --max-time 20 -o "$tmp" "$u" || { info "  [$hop] AIA fetch failed: $u"; continue; }
    certs="$work/aia.pem"
    openssl pkcs7 -inform DER -in "$tmp" -print_certs 2>/dev/null >"$certs" \
      || openssl pkcs7 -in "$tmp" -print_certs 2>/dev/null >"$certs" \
      || openssl x509 -inform DER -in "$tmp" 2>/dev/null >"$certs" || continue
    rm -f "$work"/aiaseg*.pem
    awk '/-----BEGIN CERTIFICATE-----/{n++} n>0{print > ("'"$work"'/aiaseg" n ".pem")}' "$certs"
    best=""; best_root=""
    for c in "$work"/aiaseg*.pem; do
      [ -s "$c" ] || continue
      openssl x509 -in "$c" -noout >/dev/null 2>&1 || continue
      csub=$(openssl x509 -in "$c" -noout -subject -nameopt RFC2253 2>/dev/null); csub=${csub#subject=}
      ciss=$(openssl x509 -in "$c" -noout -issuer  -nameopt RFC2253 2>/dev/null); ciss=${ciss#issuer=}
      if { [ -n "$want" ] && [ "$(ski "$c")" = "$want" ]; } \
         || { [ -z "$want" ] && [ "$csub" = "$iss" ]; }; then
        if [ "$csub" = "$ciss" ]; then best_root="$c"; else best="$c"; fi
      fi
    done
    parent="${best_root:-$best}"
    if [ -n "$parent" ]; then
      psub=$(openssl x509 -in "$parent" -noout -subject -nameopt RFC2253 2>/dev/null); psub=${psub#subject=}
      pkind="intermediate"; [ "$best_root" = "$parent" ] && pkind="SELF-SIGNED ROOT"
      echo "  [$hop] $pkind: $psub"
      echo "        found via  : $u"
      echo "        nssdb state: $(nss_status "$parent")"
      cp "$parent" "$work/hop$hop.pem"; cur="$work/hop$hop.pem"
      break
    fi
  done
  [ -n "$parent" ] || { bad "  [$hop] no parent matching AKI found in any AIA bundle for: $subj"; break; }
done

# ── 5. Verdict & recommendations ────────────────────────────────────────────
hr; echo "5. Recommendations"
echo "  Leaf issuer          : $leaf_iss"
echo "  Suggested BRANCH_FILTER for import-federal-cas.sh: '${suggest_org:-<none found>}'"
echo "    (compare against the current value; it matches case-insensitively on the CA subject)"
echo
if certutil -d "$DB" -V -u C -n "PIV_II:Certificate for PIV Authentication" </dev/null 2>/dev/null; then
  ok "certutil validates the card's PIV Authentication cert for TLS client auth NOW."
  echo "       Browsers should offer the cert. If a site still doesn't prompt, it's server-side."
else
  info "certutil could not validate the token cert (missing chain links above, or a"
  info "different token label). If any hop shows MISSING, run: import-federal-cas.sh"
  info "then import-piv-cas.sh (card inserted), and re-run this recon."
fi
hr
echo "Recon complete. Nothing was modified. Paste this output back for analysis."
RECONEOF
chmod +x ~/.local/bin/piv-card-recon.sh

# USDA/Federal and DoD certs need no card — import both now (non-fatal: a
# network hiccup must not abort the post-install run; both helpers stay on PATH
# for a manual re-run).
~/.local/bin/import-federal-cas.sh \
  || echo "WARN: Federal/USDA PKI import failed — run import-federal-cas.sh manually."
~/.local/bin/import-dod-cas.sh \
  || echo "WARN: DoD PKI import failed — run import-dod-cas.sh manually."

# The card-based chain chase is now a supplement (it catches any issuing CA the
# downward walk missed, matched exactly to YOUR card's leaf). Run it if a card
# is present; otherwise it's on PATH as import-piv-cas.sh for later.
if opensc-tool -l 2>/dev/null | grep -q 'Yes'; then
  ~/.local/bin/import-piv-cas.sh || echo "WARN: PIV CA import failed; run import-piv-cas.sh manually with the card inserted."
else
  echo "No PIV card detected (fine — Federal chain already imported card-free above)."
fi

# Self-check: prove this host's trust state right now (card-free; uses the card
# for the gold-standard leaf check only if one is inserted). Non-fatal — a
# failure prints its own FAIL lines and the helper stays on PATH for a re-run.
~/.local/bin/verify-pki-trust.sh \
  || echo "WARN: PKI self-check reported failures above — fix and re-run verify-pki-trust.sh."

#
# Fonts / desktop tweaks
# (freetype-freeworld is no longer needed — Fedora's stock freetype has
#  subpixel rendering on by default, and the old ~/.Xresources + xrdb trick
#  does nothing under Wayland. These gsettings DO work on Wayland.)
#
# Font rendering: GNOME 50 moved these out of the old gsd "xsettings" schema
# (those keys no longer exist) into org.gnome.desktop.interface. 'rgba' = subpixel.
gsettings set org.gnome.desktop.interface font-hinting 'slight'
gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
# Use Inter as the UI + document font (fontconfig family name is "Inter Variable").
gsettings set org.gnome.desktop.interface font-name 'Inter Variable 11'
gsettings set org.gnome.desktop.interface document-font-name 'Inter Variable 12'
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste true
gsettings set org.gnome.nautilus.preferences date-time-format 'detailed'

# UI quality-of-life (all Wayland-safe)
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.interface clock-show-weekday true
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface color-scheme 'default'   # light
gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'
gsettings set org.gnome.mutter center-new-windows true
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true

#
# Editor: vim is now the default (installed above); remove nano.
# (Separate dnf call — a single transaction can't both install and remove.)
#
rpm -q nano &>/dev/null && sudo dnf -y remove nano || true

#
# Automatic updates for the two things that AREN'T in a dnf repo
#
# Everything else self-updates via `dnf upgrade`: Google Chrome
# (google-chrome.repo), Microsoft Edge (microsoft-edge.repo) and VS Code
# (vscode.repo) all ship a repo. Only Ferdium (GitHub release RPM) and Signal
# (AppImage) have no repo, so each gets a small updater + a systemd timer.
# Timers beat cron here: Persistent=true catches runs missed while the machine
# was off, and output lands in the journal (journalctl -u update-ferdium etc.).

# --- Ferdium: system timer (needs root for dnf) -------------------------------
sudo tee /usr/local/sbin/update-ferdium.sh > /dev/null <<'FERDEOF'
#!/usr/bin/env bash
set -euo pipefail

api="https://api.github.com/repos/ferdium/ferdium-app/releases/latest"

# Resolve the x86_64 RPM URL, its filename, the latest-linux.yml URL, and the
# release version from the GitHub API with python3's json module (guaranteed on
# Fedora) instead of grepping JSON. There are aarch64 and x86_64 RPMs, so match
# the asset whose name ends in x86_64.rpm.
read -r url rpm_name yml_url latest < <(
  curl -fsSL "$api" | python3 -c 'import json, sys
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
rpm_url = rpm_name = yml_url = ""
for a in d.get("assets", []):
    n = a["name"]
    if n.endswith("x86_64.rpm"):
        rpm_url, rpm_name = a["browser_download_url"], n
    elif n == "latest-linux.yml":
        yml_url = a["browser_download_url"]
ver = d.get("tag_name", "").lstrip("v")
if rpm_url and yml_url and ver:
    print(rpm_url, rpm_name, yml_url, ver)'
) || true

[ -n "${url:-}" ] || { echo "Ferdium: could not resolve release assets (GitHub down/rate-limited?)"; exit 0; }

current=$(rpm -q --qf '%{VERSION}' ferdium 2>/dev/null || echo none)
if [ "$latest" = "$current" ]; then
  echo "Ferdium already at $current."
  exit 0
fi
echo "Ferdium $current -> $latest, downloading and verifying."

tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
curl -fL -o "$tmp/$rpm_name"        "$url"
curl -fL -o "$tmp/latest-linux.yml" "$yml_url"

# electron-builder records a base64-encoded SHA-512 per file in latest-linux.yml.
# Pull the one for our RPM (matched by filename) and compare it to what we
# downloaded; refuse to install on any mismatch.
expected=$(python3 -c 'import sys
target = sys.argv[1]
cur = None
for line in open(sys.argv[2]):
    s = line.strip()
    if s.startswith("- url:") or s.startswith("url:"):
        cur = s.split(":", 1)[1].strip()
    elif s.startswith("sha512:") and cur == target:
        print(s.split(":", 1)[1].strip()); break' "$rpm_name" "$tmp/latest-linux.yml")

if [ -z "$expected" ]; then
  echo "Ferdium: no sha512 for $rpm_name in latest-linux.yml; refusing to install." >&2
  exit 1
fi

computed=$(python3 -c 'import base64, hashlib, sys
print(base64.b64encode(hashlib.sha512(open(sys.argv[1], "rb").read()).digest()).decode())' "$tmp/$rpm_name")

if [ "$computed" != "$expected" ]; then
  echo "Ferdium: sha512 mismatch for $rpm_name; refusing to install." >&2
  echo "  expected: $expected" >&2
  echo "  computed: $computed" >&2
  exit 1
fi

echo "Ferdium: sha512 verified, installing from local file."
dnf -y install "$tmp/$rpm_name"
FERDEOF
sudo chmod +x /usr/local/sbin/update-ferdium.sh

sudo tee /etc/systemd/system/update-ferdium.service > /dev/null <<'EOF'
[Unit]
Description=Update Ferdium from the latest GitHub release RPM
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/update-ferdium.sh
EOF

sudo tee /etc/systemd/system/update-ferdium.timer > /dev/null <<'EOF'
[Unit]
Description=Weekly Ferdium update check

[Timer]
OnCalendar=weekly
Persistent=true
RandomizedDelaySec=2h

[Install]
WantedBy=timers.target
EOF
sudo systemctl daemon-reload
sudo systemctl enable --now update-ferdium.timer

# --- Signal: user timer (writes to ~/Applications, GPG-verified, no root) ------
# The updater script (~/.local/bin/update-signal-appimage.sh) was created in the
# Signal section above and is reused for the initial download; here we only wire
# up the timer. network-online.target is a no-op in the user manager, so the
# script itself does a connectivity check and exits cleanly if the net is down.
mkdir -p ~/.config/systemd/user
cat > ~/.config/systemd/user/update-signal.service <<'EOF'
[Unit]
Description=Update Signal Desktop AppImage

[Service]
Type=oneshot
ExecStart=%h/.local/bin/update-signal-appimage.sh
EOF

cat > ~/.config/systemd/user/update-signal.timer <<'EOF'
[Unit]
Description=Weekly Signal AppImage update check

[Timer]
OnCalendar=weekly
Persistent=true
RandomizedDelaySec=2h

[Install]
WantedBy=timers.target
EOF
systemctl --user daemon-reload
systemctl --user enable --now update-signal.timer
# The user timer only runs while you have a session. To let it run even when
# you're not logged in (Persistent catches up at next login otherwise):
#   loginctl enable-linger "$USER"

#
# Firmware updates
# fwupdmgr exits 2 for "nothing to do" (no devices / no updates), which is not a
# failure. Treat 0 and 2 as success and only warn (non-fatally) on anything else.
#
fwupd_run() {
  local rc=0
  sudo fwupdmgr "$@" || rc=$?
  case "$rc" in
    0|2) ;;
    *)   echo "WARN: 'fwupdmgr $*' exited $rc (continuing)." >&2 ;;
  esac
  return 0
}
fwupd_run refresh --force
fwupd_run update

echo "Done. Log out/in (or reboot) for shell extensions and group changes to fully apply."
echo "YubiKey: lock-on-removal and wake-on-insert are active (udev rules loaded)."
echo "         FIDO2/PAM enrollment steps are listed in the YubiKey section comments."
echo "PKI:     Federal/USDA and DoD CA bundles imported to ~/.pki/nssdb (no card"
echo "         needed) and self-checked above. On PATH for any host/user:"
echo "         verify-pki-trust.sh (fleet PASS/FAIL) and piv-card-recon.sh (deep"
echo "         diagnostics with the card inserted)."
